In [2]:
import numpy as np

# Initializing Arrays

### Manual initialization

In [3]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Array a1={}".format(a1))
print("Array a2={}".format(a2))
print("a2[1]={}".format(a2[1]))
print("a2[1][2]={}".format(a2[1][2]))
print("Shape of a2={}".format(a2.shape))

Array a1=[1 2 3 4 5]
Array a2=[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
a2[1]=[ 6  7  8  9 10]
a2[1][2]=8
Shape of a2=(2, 5)


### Standard initialization

In [4]:
a3 = np.zeros(10) # Initialize a (1x10) array with zeros
print("a3={}".format(a3))
a4 = np.zeros((5,6)) # Initialize an (5x6) array with zeros
print("a4={}".format(a4))
# print("np.zeros(1,2)={}".format( np.zeros(1,2) )) # Error: Data type not understood

a3=[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
a4=[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [5]:
print("np.ones((6,2))={}".format(np.ones((6,2))))

np.ones((6,2))=[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [6]:
print("np.full((6,2), 99)={}".format( np.full((6,2), 99) ))

np.full((6,2), 99)=[[99 99]
 [99 99]
 [99 99]
 [99 99]
 [99 99]
 [99 99]]


In [34]:
print("np.array((4,5), dtype=np.int)={}".format(  np.array((4,5), dtype=np.int)  ))

np.array((4,5), dtype=np.int)=[4 5]


In [8]:
a4_5,a4_6 = np.zeros((2,3)), np.zeros((5,6)) # Initialize multiple matrices at the same time
print ("a4_5 = {}".format(a4_5))
print ("a4_6 = {}".format(a4_6))

a4_5 = [[0. 0. 0.]
 [0. 0. 0.]]
a4_6 = [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [35]:
print("Between 1 and 20: np.linspace(1,20,17):{}".format(np.linspace(1,20,17)))
print("\nBetween 2 and 20: np.linspace(2,20,10):{}".format(np.linspace(2,20,10)))
print("\nBetween 0 and 20: np.linspace(0,20,10):{}".format(np.linspace(0,20,10)))
print("\nBetween 1 and 5: np.linspace(1,5,5):{}".format(np.linspace(1,5,5)))
print("\nBetween 0 and 5: np.linspace(0,5,6):{}".format(np.linspace(0,5,6)))

Between 1 and 20: np.linspace(1,20,17):[ 1.      2.1875  3.375   4.5625  5.75    6.9375  8.125   9.3125 10.5
 11.6875 12.875  14.0625 15.25   16.4375 17.625  18.8125 20.    ]

Between 2 and 20: np.linspace(2,20,10):[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]

Between 0 and 20: np.linspace(0,20,10):[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]

Between 1 and 5: np.linspace(1,5,5):[1. 2. 3. 4. 5.]

Between 0 and 5: np.linspace(0,5,6):[0. 1. 2. 3. 4. 5.]


In [36]:
I1 = np.eye(4)
I2 = np.eye(4)
print("I1.I20={}\n".format(np.dot(I1,I2.T)))

I1.I20=[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]



### Random initialization

In [9]:
print("np.random.randn(2,3)=\n{}\n".format(np.random.randn(2,3) ))
print("np.random.rand(2,3)=\n{}\n".format(np.random.rand(2,3) ))
print("np.random.randint(23, size=(5,3))=\n{}\n".format(np.random.randint(23, size=(5,3)) )) # Get a 5x3 matrix randomly with integer values from (1-23)
print("np.random.randint(10, 437, 23)=\n{}\n".format(np.random.randint(10, 437, 23))) # Get a 5x3 matrix randomly with integer values from (1-23)
print("\nnp.random.random((5,5))=\n{}".format(np.random.random((5,5))))

np.random.randn(2,3)=
[[ 1.14364583 -1.53404669  0.91495228]
 [-1.56262189  0.98603826  1.49451048]]

np.random.rand(2,3)=
[[0.40083004 0.41031358 0.53178205]
 [0.70258315 0.11616773 0.88052436]]

np.random.randint(23, size=(5,3))=
[[13 11 16]
 [12  8  8]
 [12  4 20]
 [ 3  8  4]
 [16  9  2]]

np.random.randint(10, 437, 23)=
[344 314  71 119 351  90 338  49 148  19  91 103 178  31 309 295 182 282
 364 142 431 361  21]


np.random.random((5,5))=
[[0.92718077 0.35599503 0.89546787 0.13135608 0.14024419]
 [0.96491096 0.68532001 0.33602022 0.04983632 0.25250813]
 [0.48754954 0.58177528 0.25492676 0.07224404 0.34344737]
 [0.56855175 0.85958001 0.52225965 0.04273554 0.88050757]
 [0.72871826 0.05998125 0.49456224 0.61418167 0.83104425]]


# Modification operations

## Insert new elements

In [10]:
d = np.random.randint(1,10,size=10)
d = np.append(d,[988]) # Append an element
print(d)

[  8   4   5   6   2   5   1   5   5   7 988]


## Reshape

In [16]:
a = np.random.randint(low=2, high=10, size=(2, 2, 3))  # low, high give the range within which the random values are generated
print("a{}=\n{}".format(a.shape, a))
print("\na reshaped to {}=\n{}".format(a.reshape((4,3)).shape, a.reshape((4,3))))
print("\na reshaped to {}=\n{}".format(a.reshape((3,4)).shape, a.reshape((3,4))))
print("\na reshaped to {}=\n{}".format(a.reshape((2,6)).shape, a.reshape((2,6))))
a_1d = a.reshape((1,12))
print("\na reshaped to {}=\n{}".format(a_1d.shape, a_1d))
print("\na_1d reshaped to {}=\n{}".format(a_1d.reshape((2,2,3)).shape, a_1d.reshape((2,2,3))))

a(2, 2, 3)=
[[[2 2 4]
  [9 8 9]]

 [[3 4 2]
  [8 7 4]]]

a reshaped to (4, 3)=
[[2 2 4]
 [9 8 9]
 [3 4 2]
 [8 7 4]]

a reshaped to (3, 4)=
[[2 2 4 9]
 [8 9 3 4]
 [2 8 7 4]]

a reshaped to (2, 6)=
[[2 2 4 9 8 9]
 [3 4 2 8 7 4]]

a reshaped to (1, 12)=
[[2 2 4 9 8 9 3 4 2 8 7 4]]

a_1d reshaped to (2, 2, 3)=
[[[2 2 4]
  [9 8 9]]

 [[3 4 2]
  [8 7 4]]]


In [17]:
a17 = np.random.random((2,4))
print("Shape of a17={}".format(a17.shape))
print("a17=\n{}\n".format(a17))

a17_reshape = a17.reshape((1,8))
print("Shape of a17_reshape={}".format(a17_reshape.shape))
print("a17_reshape=\n{}\n".format(a17_reshape))

a17_reshape2 = a17.reshape((8,1))
print("Shape of a17_reshape2={}".format(a17_reshape2.shape))
print("a17_reshape2=\n{}\n".format(a17_reshape2))

a17_reshape3 = a17.reshape((-1,4)) # Infer the first dimension of a17 automatically (-1)
print("Shape of a17_reshape3={}".format(a17_reshape3.shape))
print("a17_reshape3=\n{}\n".format(a17_reshape3))

Shape of a17=(2, 4)
a17=
[[0.41030305 0.18330038 0.04904961 0.18589634]
 [0.05515649 0.18797238 0.90479149 0.75143039]]

Shape of a17_reshape=(1, 8)
a17_reshape=
[[0.41030305 0.18330038 0.04904961 0.18589634 0.05515649 0.18797238
  0.90479149 0.75143039]]

Shape of a17_reshape2=(8, 1)
a17_reshape2=
[[0.41030305]
 [0.18330038]
 [0.04904961]
 [0.18589634]
 [0.05515649]
 [0.18797238]
 [0.90479149]
 [0.75143039]]

Shape of a17_reshape3=(2, 4)
a17_reshape3=
[[0.41030305 0.18330038 0.04904961 0.18589634]
 [0.05515649 0.18797238 0.90479149 0.75143039]]



### Convert to other shapes using standard conversion functions

In [38]:
n = 24
print("To 1D array={}".format(np.atleast_1d(n)))
print("To 2D array={}".format(np.atleast_2d(n)))
print("To 3D array={}".format(np.atleast_3d(n)))

n = [11,22,33,44]
print("To 1D array={}".format(np.atleast_1d(n)))
print("To 2D array={}".format(np.atleast_2d(n)))
print("To 3D array={}".format(np.atleast_3d(n)))

To 1D array=[24]
To 2D array=[[24]]
To 3D array=[[[24]]]
To 1D array=[11 22 33 44]
To 2D array=[[11 22 33 44]]
To 3D array=[[[11]
  [22]
  [33]
  [44]]]


## Squeeze

In [18]:
x = np.array([[[437], [233], [99]]])
print("shape of x={}; x[0][0]={}, x[0][1]={}, x[0][2]={}".format(x.shape, x[0][0], x[0][1], x[0][2]))
x_sq = np.squeeze(x)
print("shape of x_sq={}; x_sq[0]={}, x_sq[1]={}, x_sq[2]={}".format(x_sq.shape, x_sq[0], x_sq[1], x_sq[2]))

shape of x=(1, 3, 1); x[0][0]=[437], x[0][1]=[233], x[0][2]=[99]
shape of x_sq=(3,); x_sq[0]=437, x_sq[1]=233, x_sq[2]=99


## Slicing

Syntax: x[start:stop:step]

If any of these are unspecified, they default to the values 
* start= 0
* stop = size of dimension
* step = 1

In [19]:
# Example-1
np.random.seed(67)
x = np.random.randint(9, size=(10,6))
print("x={}".format(x))
print("\nx[1::4]=\n{}".format(x[1::4]))
print("\nx[1::2]=\n{}".format(x[1::2]))
print("\nx[1:2:4]=\n{}".format(x[1:2:4]))
print("\nx[1:4:2]=\n{}".format(x[1:4:2]))

x=[[3 5 5 7 3 6]
 [3 7 8 5 3 6]
 [4 7 1 3 7 8]
 [7 2 5 5 3 2]
 [6 6 4 8 3 1]
 [4 8 2 7 0 7]
 [7 5 2 0 7 3]
 [5 1 6 1 3 4]
 [5 0 8 5 5 2]
 [8 7 6 3 4 1]]

x[1::4]=
[[3 7 8 5 3 6]
 [4 8 2 7 0 7]
 [8 7 6 3 4 1]]

x[1::2]=
[[3 7 8 5 3 6]
 [7 2 5 5 3 2]
 [4 8 2 7 0 7]
 [5 1 6 1 3 4]
 [8 7 6 3 4 1]]

x[1:2:4]=
[[3 7 8 5 3 6]]

x[1:4:2]=
[[3 7 8 5 3 6]
 [7 2 5 5 3 2]]


In [20]:
a = np.array([range(v,v+3) for v in [1, 4, 7, 10]])
b = np.array([range(v,v+3) for v in [13,16, 19, 22]])
print("a={}\nb={}\n".format(a,b))
print("First 2-rows and 3-columns of a={}".format(a[:2,:3]))
print("First 2-rows and 2-columns of a={}".format(a[:2,:2]))
print("Last 2-rows and last 2-columns of a={}".format(a[2:4:,1:3:]))
print("Last 2-rows and last 2-columns of a={}".format(a[2::,1::]))
print("Middle of matrix a={}".format(a[1:3,1:3]))

a=[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
b=[[13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]]

First 2-rows and 3-columns of a=[[1 2 3]
 [4 5 6]]
First 2-rows and 2-columns of a=[[1 2]
 [4 5]]
Last 2-rows and last 2-columns of a=[[ 8  9]
 [11 12]]
Last 2-rows and last 2-columns of a=[[ 8  9]
 [11 12]]
Middle of matrix a=[[5 6]
 [8 9]]


To 1D array=[24]
To 2D array=[[24]]
To 3D array=[[[24]]]
To 1D array=[11 22 33 44]
To 2D array=[[11 22 33 44]]
To 3D array=[[[11]
  [22]
  [33]
  [44]]]


## Axes
### Summation

In [25]:
# Two dimentional arrays
a = np.ones([3,5])
b = np.random.randint(1,10,[3,5])
print("a={}\n\nb={}".format(a,b))

# Summation along axis
print("\nSum of a, along axis0 = {}".format(np.sum(a,axis=0)))
print("\nSum of a, along axis1 = {}".format(np.sum(a,axis=1)))
print("\nSum of b, along axis0 = {}".format(np.sum(b,axis=0)))
print("\nSum of b, along axis1 = {}".format(np.sum(b,axis=1)))

# Concatenation along axis
print("\nConcatenate a and b along axis-0={}".format(np.concatenate([a,b], axis=0)))
print("\nConcatenate a and b along axis-1={}".format(np.concatenate([a,b], axis=1)))

a=[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

b=[[9 3 6 2 8]
 [3 4 6 2 7]
 [7 1 5 5 4]]

Sum of a, along axis0 = [3. 3. 3. 3. 3.]

Sum of a, along axis1 = [5. 5. 5.]

Sum of b, along axis0 = [19  8 17  9 19]

Sum of b, along axis1 = [28 22 22]

Concatenate a and b along axis-0=[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [9. 3. 6. 2. 8.]
 [3. 4. 6. 2. 7.]
 [7. 1. 5. 5. 4.]]

Concatenate a and b along axis-1=[[1. 1. 1. 1. 1. 9. 3. 6. 2. 8.]
 [1. 1. 1. 1. 1. 3. 4. 6. 2. 7.]
 [1. 1. 1. 1. 1. 7. 1. 5. 5. 4.]]


In [26]:
# Three dimentional array
a = np.ones([3,5,2])
b = np.random.randint(1,10,[3,5,2])
print("a={}\n\nb={}".format(a,b))

# Summation along axis
print("\nSum of a, along axis0 = {}".format(np.sum(a,axis=0)))
print("\nSum of a, along axis1 = {}".format(np.sum(a,axis=1)))
print("\nSum of a, along axis2 = {}".format(np.sum(a,axis=2)))
print("\nSum of b, along axis0 = {}".format(np.sum(b,axis=0)))
print("\nSum of b, along axis1 = {}".format(np.sum(b,axis=1)))
print("\nSum of b, along axis2 = {}".format(np.sum(b,axis=2)))

# Concatenation along axis
print("\nConcatenate a and b along axis-0={}".format(np.concatenate([a,b], axis=0)))
print("\nConcatenate a and b along axis-1={}".format(np.concatenate([a,b], axis=1)))
print("\nConcatenate a and b along axis-2={}".format(np.concatenate([a,b], axis=2)))

# References

* [Numpy axes explained](https://www.sharpsightlabs.com/blog/numpy-axes-explained/)

a=[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]

b=[[[5 1]
  [2 6]
  [9 4]
  [9 2]
  [1 8]]

 [[5 9]
  [1 5]
  [3 1]
  [9 3]
  [6 3]]

 [[3 4]
  [1 8]
  [8 4]
  [6 3]
  [2 2]]]

Sum of a, along axis0 = [[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]

Sum of a, along axis1 = [[5. 5.]
 [5. 5.]
 [5. 5.]]

Sum of a, along axis2 = [[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]

Sum of b, along axis0 = [[13 14]
 [ 4 19]
 [20  9]
 [24  8]
 [ 9 13]]

Sum of b, along axis1 = [[26 21]
 [24 21]
 [20 21]]

Sum of b, along axis2 = [[ 6  8 13 11  9]
 [14  6  4 12  9]
 [ 7  9 12  9  4]]

Concatenate a and b along axis-0=[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[5. 1.]
  [2. 6.]
  [9. 4.]
  [9. 2.]
  [1. 8.]]

 [[5. 9.]
  [1. 5.]
  [3. 1.]
  [9. 3.]
  [6. 3.]]

 [[3. 4.]
 

# Array (standard) operations

In [37]:
a4 = np.random.randn(2,3)
a5 = np.exp(a4) # Create a new array, same rank as a4_3, whose values are exponential of corresponding values of a4_3
print("a5(exp of array a4)=\n{}\n".format(a5))

a5_1 = np.log(a5) # Create a new array, same rank as a5, whose values are logarithmic to the values of a5
print("a5_1(log of array a5)=\n{}".format(a5_1))
print("\nOperation 1-a5_1=\n{}\n".format(1-a5_1))

a5_2 = np.array(abs(a5)) 
print("abs of a5=\n{}".format(a5_2))

a5(exp of array a4)=
[[1.5149652  1.77564105 0.33782228]
 [0.90799112 0.26773996 1.19079353]]

a5_1(log of array a5)=
[[ 0.41539247  0.57416151 -1.08523531]
 [-0.09652069 -1.31773906  0.17461992]]

Operation 1-a5_1=
[[0.58460753 0.42583849 2.08523531]
 [1.09652069 2.31773906 0.82538008]]

abs of a5=
[[1.5149652  1.77564105 0.33782228]
 [0.90799112 0.26773996 1.19079353]]


## Copying an array into another

In [13]:
a1 = np.random.randn(2,3)
print("a1=\n{}".format(a1))
a2 = a1.copy() # Copy an array
a2 /= 2
print("Operation divide by 2 of matrix a2=\n{}".format(a2))

a1=
[[-1.12034375 -1.04453515  1.29286174]
 [ 0.20276721 -0.56928888 -0.68364355]]
Operation divide by 2 of matrix a2=
[[-0.56017188 -0.52226757  0.64643087]
 [ 0.10138361 -0.28464444 -0.34182178]]


## Elementwise mathematical operations

In [14]:
# Note that all the operations below are element wise. 

a5_2 = np.random.randint(45,size=(2,3))
a5_3 = np.ones((2,3))
print("a5_2=\n{}\n\na5_3=\n{}\n".format(a5_2, a5_3))

# Addition
print("Addition operations\n")
a5_4 = np.add(a5_2,a5_3)
print("a5_2+a5_3=\n{}\n".format(a5_4))
a5_4_1 = np.add(22,a5_3)
print("22+a5_3=\n{}\n".format(a5_4_1))
a5_4_2 = np.add(a5_3,22)
print("a5_3+22=\n{}\n".format(a5_4_2))

print("Subtraction operations\n")
a5_5 = np.subtract(a5_2,a5_3)
print("a5_2-a5_3=\n{}\n".format(a5_5))

print("Multiplication operations\n")
a5_6 = np.multiply(a5_2,a5_3) 
print("a5_2*a5_3=\n{}\n".format(a5_6))
a5_6_1 = np.multiply(437,a5_3) 
print("437*a5_3=\n{}\n".format(a5_6_1))
a5_6_2 = np.multiply(a5_3,437) 
print("a5_3*437=\n{}\n".format(a5_6_2))

print("Division operations\n")
a5_7 = np.divide(a5_2,a5_3)
print("a5_2/a5_3=\n{}\n".format(a5_7))

print("Miscelleneous operations\n")
a5_8 = np.square(a5_2)
print("elementwise (a5_2)^2=\n{}".format(a5_8))

a5_9 = np.sqrt(a5_8)
print("\nsqrt(a5_8)=\n{}".format(a5_8))

a5_2=
[[38 10 38]
 [24 27 22]]

a5_3=
[[1. 1. 1.]
 [1. 1. 1.]]

Addition operations

a5_2+a5_3=
[[39. 11. 39.]
 [25. 28. 23.]]

22+a5_3=
[[23. 23. 23.]
 [23. 23. 23.]]

a5_3+22=
[[23. 23. 23.]
 [23. 23. 23.]]

Subtraction operations

a5_2-a5_3=
[[37.  9. 37.]
 [23. 26. 21.]]

Multiplication operations

a5_2*a5_3=
[[38. 10. 38.]
 [24. 27. 22.]]

437*a5_3=
[[437. 437. 437.]
 [437. 437. 437.]]

a5_3*437=
[[437. 437. 437.]
 [437. 437. 437.]]

Division operations

a5_2/a5_3=
[[38. 10. 38.]
 [24. 27. 22.]]

Miscelleneous operations

elementwise (a5_2)^2=
[[1444  100 1444]
 [ 576  729  484]]

sqrt(a5_8)=
[[1444  100 1444]
 [ 576  729  484]]


## Matrix operations

In [15]:
a14 = np.array([[1,1,1], [2,2,2]])
a15 = np.array([[1],[2],[3]])
print("a14=\n{}\n\na15=\n{}\n".format(a14, a15))
print("np.dot operation of matrix shapes {} and {} is a {} shaped matrix = \n{}".format(a14.shape, a15.shape, np.dot(a14,a15).shape, np.dot(a14,a15)))

a14=
[[1 1 1]
 [2 2 2]]

a15=
[[1]
 [2]
 [3]]

np.dot operation of matrix shapes (2, 3) and (3, 1) is a (2, 1) shaped matrix = 
[[ 6]
 [12]]


## Applying functions on all elements
### Square each item in the array

In [21]:
x = np.array([1, 2, 3, 4, 5])
f = lambda x: x ** 2
squares = f(x)
#print(squares)
print("squares={}\nUsing np.square(x)={}".format(squares, np.square(x)))

squares=[ 1  4  9 16 25]
Using np.square(x)=[ 1  4  9 16 25]


### Applying sigmoid function (1/(1+e^-z))

In [22]:
a = np.random.randint(20, size=(3,4))
a_sigmoid = 1/(1+np.exp(-a))
print("Applying sigmoid function to all the elements:\n{}".format(a_sigmoid))

Applying sigmoid function to all the elements:
[[0.99966465 0.5        0.73105858 0.99966465]
 [0.99999386 0.99999989 0.99999917 0.99999917]
 [0.9999833  0.99330715 0.99999989 0.98201379]]


### Return True/False based on some threshold

In [23]:
x = np.array([1, 2, 3, 4, 5])
threshold = 2.9
one_zeros = x > threshold
print(one_zeros)

[False False  True  True  True]


# Accessing  array elements
## Individual elements of the array

In [11]:
a16 = np.array([[1,2,3,4,5,6]])
print("a16=\n{}\n\na16[0][5]={}".format(a16,a16[0][5]))

a16=
[[1 2 3 4 5 6]]

a16[0][5]=6


# References

* [Numpy axes explained](https://www.sharpsightlabs.com/blog/numpy-axes-explained/)