In [2]:
import numpy as np

# Notes

* In NumPy dimentions are called as **axes**

# Initializing Arrays

### General initializing techniques and accessors

In [3]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Array a1={}".format(a1))
print("Array a2={}".format(a2))
print("a2[1]={}".format(a2[1]))
print("a2[1][2]={}".format(a2[1][2]))
print("Shape of a2={}".format(a2.shape))

Array a1=[1 2 3 4 5]
Array a2=[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
a2[1]=[ 6  7  8  9 10]
a2[1][2]=8
Shape of a2=(2, 5)


### Standard initialization

In [4]:
a3 = np.zeros(10) # Initialize a (1x10) array with zeros
print("a3={}".format(a3))
a4 = np.zeros((5,6)) # Initialize an (5x6) array with zeros
print("a4={}".format(a4))
# print("np.zeros(1,2)={}".format( np.zeros(1,2) )) # Error: Data type not understood

a3=[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
a4=[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [5]:
print("np.ones((6,2))={}".format(np.ones((6,2))))

np.ones((6,2))=[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [6]:
print("np.full((6,2), 99)={}".format( np.full((6,2), 99) ))

np.full((6,2), 99)=[[99 99]
 [99 99]
 [99 99]
 [99 99]
 [99 99]
 [99 99]]


In [7]:
print("np.array((4,5), dtype=np.int)={}".format(  np.array((4,5), dtype=np.int)  ))

np.array((4,5), dtype=np.int)=[4 5]


In [8]:
a4_5,a4_6 = np.zeros((2,3)), np.zeros((5,6)) # Initialize multiple matrices at the same time
print ("a4_5 = {}".format(a4_5))
print ("a4_6 = {}".format(a4_6))

a4_5 = [[0. 0. 0.]
 [0. 0. 0.]]
a4_6 = [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


### Random initialization

In [9]:
print("np.random.randn(2,3)=\n{}\n".format(np.random.randn(2,3) ))
print("np.random.rand(2,3)=\n{}\n".format(np.random.rand(2,3) ))
print("np.random.randint(23, size=(5,3))=\n{}\n".format(np.random.randint(23, size=(5,3)) )) # Get a 5x3 matrix randomly with integer values from (1-23)
print("np.random.randint(10, 437, 23)=\n{}\n".format(np.random.randint(10, 437, 23))) # Get a 5x3 matrix randomly with integer values from (1-23)
print("\nnp.random.random((5,5))=\n{}".format(np.random.random((5,5))))

np.random.randn(2,3)=
[[-0.64682542  0.64409754 -1.17064707]
 [-0.69625521  0.35004473  1.58393772]]

np.random.rand(2,3)=
[[0.34772266 0.24398522 0.82222432]
 [0.0573048  0.22861204 0.90331414]]

np.random.randint(23, size=(5,3))=
[[ 6 21 20]
 [11  4 11]
 [ 4 10 10]
 [13 16 21]
 [ 6 22 18]]

np.random.randint(10, 437, 23)=
[383 249 239 319 213 405 256 303 278 244 326 235 220  54 238 138  50 418
  74 403 280 384  40]


np.random.random((5,5))=
[[2.56191027e-01 9.93330608e-01 9.04908754e-01 7.17936527e-01
  2.14946426e-01]
 [1.63730818e-01 6.11985726e-01 2.79993688e-01 2.91622272e-01
  5.31750880e-01]
 [9.24447174e-01 1.87312535e-01 5.04500120e-01 7.05531216e-01
  4.31103040e-01]
 [8.25818234e-04 9.66262066e-01 8.65255267e-01 1.65979899e-01
  1.10259647e-01]
 [2.02143988e-01 6.74648449e-01 9.83515558e-01 3.63951276e-02
  1.06687672e-01]]


# Modification operations

## Insert new elements

In [29]:
d = np.random.randint(1,10,size=10)
d = np.append(d,[988]) # Append an element
print(d)

[  7   9   3   8   3   7   6   7   6   3 988]


# Accessing  array elements
## Individual elements of the array

In [11]:
a16 = np.array([[1,2,3,4,5,6]])
print("a16=\n{}\n\na16[0][5]={}".format(a16,a16[0][5]))

a16=
[[1 2 3 4 5 6]]

a16[0][5]=6


# Array (standard) operations

In [12]:
a4 = np.random.randn(2,3)
a5 = np.exp(a4) # Create a new array, same rank as a4_3, whose values are exponential of corresponding values of a4_3
print("a5(exp of array a4)=\n{}\n".format(a5))

a5_1 = np.log(a5) # Create a new array, same rank as a5, whose values are logarithmic to the values of a5
print("a5_1(log of array a5)=\n{}".format(a5_1))
print("\nOperation 1-a5_1=\n{}\n".format(1-a5_1))

a5_2 = np.array(abs(a5)) 
print("abs of a5=\n{}".format(a5_2))

a5(exp of array a4)=
[[0.49840106 1.09286667 0.7130938 ]
 [0.43439323 0.58786542 4.55323909]]

a5_1(log of array a5)=
[[-0.69635019  0.08880422 -0.33814231]
 [-0.8338051  -0.53125723  1.51583887]]

Operation 1-a5_1=
[[ 1.69635019  0.91119578  1.33814231]
 [ 1.8338051   1.53125723 -0.51583887]]

abs of a5=
[[0.49840106 1.09286667 0.7130938 ]
 [0.43439323 0.58786542 4.55323909]]


## Copying an array into another

In [13]:
a1 = np.random.randn(2,3)
print("a1=\n{}".format(a1))
a2 = a1.copy() # Copy an array
a2 /= 2
print("Operation divide by 2 of matrix a2=\n{}".format(a2))

a1=
[[-0.32228819 -1.35185193  1.71902993]
 [ 0.02713377 -0.28577263  0.37472262]]
Operation divide by 2 of matrix a2=
[[-0.16114409 -0.67592596  0.85951497]
 [ 0.01356689 -0.14288632  0.18736131]]


## Elementwise mathematical operations

In [14]:
# Note that all the operations below are element wise. 

a5_2 = np.random.randint(45,size=(2,3))
a5_3 = np.ones((2,3))
print("a5_2=\n{}\n\na5_3=\n{}\n".format(a5_2, a5_3))

# Addition
print("Addition operations\n")
a5_4 = np.add(a5_2,a5_3)
print("a5_2+a5_3=\n{}\n".format(a5_4))
a5_4_1 = np.add(22,a5_3)
print("22+a5_3=\n{}\n".format(a5_4_1))
a5_4_2 = np.add(a5_3,22)
print("a5_3+22=\n{}\n".format(a5_4_2))

print("Subtraction operations\n")
a5_5 = np.subtract(a5_2,a5_3)
print("a5_2-a5_3=\n{}\n".format(a5_5))

print("Multiplication operations\n")
a5_6 = np.multiply(a5_2,a5_3) 
print("a5_2*a5_3=\n{}\n".format(a5_6))
a5_6_1 = np.multiply(437,a5_3) 
print("437*a5_3=\n{}\n".format(a5_6_1))
a5_6_2 = np.multiply(a5_3,437) 
print("a5_3*437=\n{}\n".format(a5_6_2))

print("Division operations\n")
a5_7 = np.divide(a5_2,a5_3)
print("a5_2/a5_3=\n{}\n".format(a5_7))

print("Miscelleneous operations\n")
a5_8 = np.square(a5_2)
print("elementwise (a5_2)^2=\n{}".format(a5_8))

a5_9 = np.sqrt(a5_8)
print("\nsqrt(a5_8)=\n{}".format(a5_8))

a5_2=
[[ 9 42  3]
 [38 18 18]]

a5_3=
[[1. 1. 1.]
 [1. 1. 1.]]

Addition operations

a5_2+a5_3=
[[10. 43.  4.]
 [39. 19. 19.]]

22+a5_3=
[[23. 23. 23.]
 [23. 23. 23.]]

a5_3+22=
[[23. 23. 23.]
 [23. 23. 23.]]

Subtraction operations

a5_2-a5_3=
[[ 8. 41.  2.]
 [37. 17. 17.]]

Multiplication operations

a5_2*a5_3=
[[ 9. 42.  3.]
 [38. 18. 18.]]

437*a5_3=
[[437. 437. 437.]
 [437. 437. 437.]]

a5_3*437=
[[437. 437. 437.]
 [437. 437. 437.]]

Division operations

a5_2/a5_3=
[[ 9. 42.  3.]
 [38. 18. 18.]]

Miscelleneous operations

elementwise (a5_2)^2=
[[  81 1764    9]
 [1444  324  324]]

sqrt(a5_8)=
[[  81 1764    9]
 [1444  324  324]]


## Matrix operations

In [15]:
a14 = np.array([[1,1,1], [2,2,2]])
a15 = np.array([[1],[2],[3]])
print("a14=\n{}\n\na15=\n{}\n".format(a14, a15))
print("np.dot operation of matrix shapes {} and {} is a {} shaped matrix = \n{}".format(a14.shape, a15.shape, np.dot(a14,a15).shape, np.dot(a14,a15)))

a14=
[[1 1 1]
 [2 2 2]]

a15=
[[1]
 [2]
 [3]]

np.dot operation of matrix shapes (2, 3) and (3, 1) is a (2, 1) shaped matrix = 
[[ 6]
 [12]]


## Reshape

In [16]:
a = np.random.randint(low=2, high=10, size=(2, 2, 3))  # low, high give the range within which the random values are generated
print("a{}=\n{}".format(a.shape, a))
print("\na reshaped to {}=\n{}".format(a.reshape((4,3)).shape, a.reshape((4,3))))
print("\na reshaped to {}=\n{}".format(a.reshape((3,4)).shape, a.reshape((3,4))))
print("\na reshaped to {}=\n{}".format(a.reshape((2,6)).shape, a.reshape((2,6))))
a_1d = a.reshape((1,12))
print("\na reshaped to {}=\n{}".format(a_1d.shape, a_1d))
print("\na_1d reshaped to {}=\n{}".format(a_1d.reshape((2,2,3)).shape, a_1d.reshape((2,2,3))))

a(2, 2, 3)=
[[[8 8 6]
  [7 3 7]]

 [[6 9 7]
  [9 4 2]]]

a reshaped to (4, 3)=
[[8 8 6]
 [7 3 7]
 [6 9 7]
 [9 4 2]]

a reshaped to (3, 4)=
[[8 8 6 7]
 [3 7 6 9]
 [7 9 4 2]]

a reshaped to (2, 6)=
[[8 8 6 7 3 7]
 [6 9 7 9 4 2]]

a reshaped to (1, 12)=
[[8 8 6 7 3 7 6 9 7 9 4 2]]

a_1d reshaped to (2, 2, 3)=
[[[8 8 6]
  [7 3 7]]

 [[6 9 7]
  [9 4 2]]]


In [17]:
a17 = np.random.random((2,4))
print("Shape of a17={}".format(a17.shape))
print("a17=\n{}\n".format(a17))

a17_reshape = a17.reshape((1,8))
print("Shape of a17_reshape={}".format(a17_reshape.shape))
print("a17_reshape=\n{}\n".format(a17_reshape))

a17_reshape2 = a17.reshape((8,1))
print("Shape of a17_reshape2={}".format(a17_reshape2.shape))
print("a17_reshape2=\n{}\n".format(a17_reshape2))

a17_reshape3 = a17.reshape((-1,4)) # Infer the first dimension of a17 automatically (-1)
print("Shape of a17_reshape3={}".format(a17_reshape3.shape))
print("a17_reshape3=\n{}\n".format(a17_reshape3))

Shape of a17=(2, 4)
a17=
[[0.00340142 0.03470074 0.31423804 0.71300628]
 [0.22202267 0.79108392 0.35661904 0.63758621]]

Shape of a17_reshape=(1, 8)
a17_reshape=
[[0.00340142 0.03470074 0.31423804 0.71300628 0.22202267 0.79108392
  0.35661904 0.63758621]]

Shape of a17_reshape2=(8, 1)
a17_reshape2=
[[0.00340142]
 [0.03470074]
 [0.31423804]
 [0.71300628]
 [0.22202267]
 [0.79108392]
 [0.35661904]
 [0.63758621]]

Shape of a17_reshape3=(2, 4)
a17_reshape3=
[[0.00340142 0.03470074 0.31423804 0.71300628]
 [0.22202267 0.79108392 0.35661904 0.63758621]]



## Squeeze

In [18]:
x = np.array([[[437], [233], [99]]])
print("shape of x={}; x[0][0]={}, x[0][1]={}, x[0][2]={}".format(x.shape, x[0][0], x[0][1], x[0][2]))
x_sq = np.squeeze(x)
print("shape of x_sq={}; x_sq[0]={}, x_sq[1]={}, x_sq[2]={}".format(x_sq.shape, x_sq[0], x_sq[1], x_sq[2]))

shape of x=(1, 3, 1); x[0][0]=[437], x[0][1]=[233], x[0][2]=[99]
shape of x_sq=(3,); x_sq[0]=437, x_sq[1]=233, x_sq[2]=99


## Slicing

In [19]:
np.random.seed(67)
x = np.random.randint(9, size=(10,6))
print("x={}".format(x))
print("\nx[1::4]=\n{}".format(x[1::4]))
print("\nx[1::2]=\n{}".format(x[1::2]))
print("\nx[1:2:4]=\n{}".format(x[1:2:4]))
print("\nx[1:4:2]=\n{}".format(x[1:4:2]))

x=[[3 5 5 7 3 6]
 [3 7 8 5 3 6]
 [4 7 1 3 7 8]
 [7 2 5 5 3 2]
 [6 6 4 8 3 1]
 [4 8 2 7 0 7]
 [7 5 2 0 7 3]
 [5 1 6 1 3 4]
 [5 0 8 5 5 2]
 [8 7 6 3 4 1]]

x[1::4]=
[[3 7 8 5 3 6]
 [4 8 2 7 0 7]
 [8 7 6 3 4 1]]

x[1::2]=
[[3 7 8 5 3 6]
 [7 2 5 5 3 2]
 [4 8 2 7 0 7]
 [5 1 6 1 3 4]
 [8 7 6 3 4 1]]

x[1:2:4]=
[[3 7 8 5 3 6]]

x[1:4:2]=
[[3 7 8 5 3 6]
 [7 2 5 5 3 2]]


## Applying functions on all elements
### Square each item in the array

In [20]:
x = np.array([1, 2, 3, 4, 5])
f = lambda x: x ** 2
squares = f(x)
#print(squares)
print("squares={}\nUsing np.square(x)={}".format(squares, np.square(x)))

squares=[ 1  4  9 16 25]
Using np.square(x)=[ 1  4  9 16 25]


### Applying sigmoid function (1/(1+e^-z))

In [21]:
a = np.random.randint(20, size=(3,4))
a_sigmoid = 1/(1+np.exp(-a))
print("Applying sigmoid function to all the elements:\n{}".format(a_sigmoid))

Applying sigmoid function to all the elements:
[[0.99966465 0.5        0.73105858 0.99966465]
 [0.99999386 0.99999989 0.99999917 0.99999917]
 [0.9999833  0.99330715 0.99999989 0.98201379]]


### Return True/False based on some threshold

In [22]:
x = np.array([1, 2, 3, 4, 5])
threshold = 2.9
one_zeros = x > threshold
print(one_zeros)

[False False  True  True  True]


## Conversion

In [23]:
n = 24
print("To 1D array={}".format(np.atleast_1d(n)))
print("To 2D array={}".format(np.atleast_2d(n)))
print("To 3D array={}".format(np.atleast_3d(n)))

n = [11,22,33,44]
print("To 1D array={}".format(np.atleast_1d(n)))
print("To 2D array={}".format(np.atleast_2d(n)))
print("To 3D array={}".format(np.atleast_3d(n)))

To 1D array=[24]
To 2D array=[[24]]
To 3D array=[[[24]]]
To 1D array=[11 22 33 44]
To 2D array=[[11 22 33 44]]
To 3D array=[[[11]
  [22]
  [33]
  [44]]]
