In [1]:
import numpy as np

# Initializing Arrays

### General initializing techniques and accessors

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Array a1={}".format(a1))
print("Array a2={}".format(a2))
print("a2[1]={}".format(a2[1]))
print("a2[1][2]={}".format(a2[1][2]))
print("Shape of a2={}".format(a2.shape))

Array a1=[1 2 3 4 5]
Array a2=[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
a2[1]=[ 6  7  8  9 10]
a2[1][2]=8
Shape of a2=(2, 5)


### Standard initialization

In [3]:
a3 = np.zeros(10) # Initialize a (1x10) array with zeros
print("a3={}".format(a3))
a4 = np.zeros((5,6)) # Initialize an (5x6) array with zeros
print("a4={}".format(a4))
# print("np.zeros(1,2)={}".format( np.zeros(1,2) )) # Error: Data type not understood

a3=[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
a4=[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [4]:
print("np.ones((6,2))={}".format(np.ones((6,2))))

np.ones((6,2))=[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [5]:
print("np.full((6,2), 99)={}".format( np.full((6,2), 99) ))

np.full((6,2), 99)=[[99 99]
 [99 99]
 [99 99]
 [99 99]
 [99 99]
 [99 99]]


In [6]:
print("np.array((4,5), dtype=np.int)={}".format(  np.array((4,5), dtype=np.int)  ))

np.array((4,5), dtype=np.int)=[4 5]


In [7]:
a4_5,a4_6 = np.zeros((2,3)), np.zeros((5,6)) # Initialize multiple matrices at the same time
print ("a4_5 = {}".format(a4_5))
print ("a4_6 = {}".format(a4_6))

a4_5 = [[0. 0. 0.]
 [0. 0. 0.]]
a4_6 = [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


### Random initialization

In [8]:
print("np.random.randn(2,3)=\n{}\n".format(np.random.randn(2,3) ))
print("np.random.rand(2,3)=\n{}\n".format(np.random.rand(2,3) ))
print("np.random.randint(23, size=(5,3))=\n{}\n".format(np.random.randint(23, size=(5,3)) )) # Get a 5x3 matrix randomly with integer values from (1-23)
print("np.random.randint(10, 437, 23)=\n{}\n".format(np.random.randint(10, 437, 23))) # Get a 5x3 matrix randomly with integer values from (1-23)
print("\nnp.random.random((5,5))=\n{}".format(np.random.random((5,5))))

np.random.randn(2,3)=
[[-0.48798629 -0.41449353 -0.24515339]
 [-0.73727401 -0.45904658  0.41510459]]

np.random.rand(2,3)=
[[0.02518123 0.36865305 0.86571196]
 [0.58849477 0.9555399  0.56137371]]

np.random.randint(23, size=(5,3))=
[[ 2  7  1]
 [ 8 15 16]
 [22 10 14]
 [ 0 20  0]
 [17  6 18]]

np.random.randint(10, 437, 23)=
[245 109 106 420 266 242 266 233  89  55 370 186  70 187  37 202 329 385
  24 181 208  42  36]


np.random.random((5,5))=
[[0.97971218 0.73131861 0.23309199 0.85502487 0.65062005]
 [0.49831547 0.8813217  0.07802431 0.96642203 0.89897011]
 [0.22172272 0.83465723 0.35592099 0.54841749 0.05927039]
 [0.2969374  0.30287974 0.03811513 0.29750817 0.73234716]
 [0.24937229 0.20531678 0.1867922  0.32274062 0.97570606]]


# Modification operations

## Insert new elements

In [9]:
d = np.random.randint(1,10,size=10)
d = np.append(d,[988]) # Append an element
print(d)

[  7   8   9   4   6   3   8   2   1   3 988]


# Accessing  array elements
## Individual elements of the array

In [10]:
a16 = np.array([[1,2,3,4,5,6]])
print("a16=\n{}\n\na16[0][5]={}".format(a16,a16[0][5]))

a16=
[[1 2 3 4 5 6]]

a16[0][5]=6


# Array (standard) operations

In [11]:
a4 = np.random.randn(2,3)
a5 = np.exp(a4) # Create a new array, same rank as a4_3, whose values are exponential of corresponding values of a4_3
print("a5(exp of array a4)=\n{}\n".format(a5))

a5_1 = np.log(a5) # Create a new array, same rank as a5, whose values are logarithmic to the values of a5
print("a5_1(log of array a5)=\n{}".format(a5_1))
print("\nOperation 1-a5_1=\n{}\n".format(1-a5_1))

a5_2 = np.array(abs(a5)) 
print("abs of a5=\n{}".format(a5_2))

a5(exp of array a4)=
[[0.2727636  1.46890134 1.03840177]
 [0.39418057 2.66743044 1.09979213]]

a5_1(log of array a5)=
[[-1.29914981  0.38451473  0.03768277]
 [-0.93094618  0.98111563  0.09512119]]

Operation 1-a5_1=
[[2.29914981 0.61548527 0.96231723]
 [1.93094618 0.01888437 0.90487881]]

abs of a5=
[[0.2727636  1.46890134 1.03840177]
 [0.39418057 2.66743044 1.09979213]]


## Copying an array into another

In [12]:
a1 = np.random.randn(2,3)
print("a1=\n{}".format(a1))
a2 = a1.copy() # Copy an array
a2 /= 2
print("Operation divide by 2 of matrix a2=\n{}".format(a2))

a1=
[[-0.40841845  0.25903953  1.87993743]
 [ 0.9906212  -0.09682044  0.07685643]]
Operation divide by 2 of matrix a2=
[[-0.20420922  0.12951977  0.93996871]
 [ 0.4953106  -0.04841022  0.03842821]]


## Elementwise mathematical operations

In [13]:
# Note that all the operations below are element wise. 

a5_2 = np.random.randint(45,size=(2,3))
a5_3 = np.ones((2,3))
print("a5_2=\n{}\n\na5_3=\n{}\n".format(a5_2, a5_3))

# Addition
print("Addition operations\n")
a5_4 = np.add(a5_2,a5_3)
print("a5_2+a5_3=\n{}\n".format(a5_4))
a5_4_1 = np.add(22,a5_3)
print("22+a5_3=\n{}\n".format(a5_4_1))
a5_4_2 = np.add(a5_3,22)
print("a5_3+22=\n{}\n".format(a5_4_2))

print("Subtraction operations\n")
a5_5 = np.subtract(a5_2,a5_3)
print("a5_2-a5_3=\n{}\n".format(a5_5))

print("Multiplication operations\n")
a5_6 = np.multiply(a5_2,a5_3) 
print("a5_2*a5_3=\n{}\n".format(a5_6))
a5_6_1 = np.multiply(437,a5_3) 
print("437*a5_3=\n{}\n".format(a5_6_1))
a5_6_2 = np.multiply(a5_3,437) 
print("a5_3*437=\n{}\n".format(a5_6_2))

print("Division operations\n")
a5_7 = np.divide(a5_2,a5_3)
print("a5_2/a5_3=\n{}\n".format(a5_7))

print("Miscelleneous operations\n")
a5_8 = np.square(a5_2)
print("elementwise (a5_2)^2=\n{}".format(a5_8))

a5_9 = np.sqrt(a5_8)
print("\nsqrt(a5_8)=\n{}".format(a5_8))

a5_2=
[[16 36  8]
 [39 26 14]]

a5_3=
[[1. 1. 1.]
 [1. 1. 1.]]

Addition operations

a5_2+a5_3=
[[17. 37.  9.]
 [40. 27. 15.]]

22+a5_3=
[[23. 23. 23.]
 [23. 23. 23.]]

a5_3+22=
[[23. 23. 23.]
 [23. 23. 23.]]

Subtraction operations

a5_2-a5_3=
[[15. 35.  7.]
 [38. 25. 13.]]

Multiplication operations

a5_2*a5_3=
[[16. 36.  8.]
 [39. 26. 14.]]

437*a5_3=
[[437. 437. 437.]
 [437. 437. 437.]]

a5_3*437=
[[437. 437. 437.]
 [437. 437. 437.]]

Division operations

a5_2/a5_3=
[[16. 36.  8.]
 [39. 26. 14.]]

Miscelleneous operations

elementwise (a5_2)^2=
[[ 256 1296   64]
 [1521  676  196]]

sqrt(a5_8)=
[[ 256 1296   64]
 [1521  676  196]]


## Matrix operations

In [14]:
a14 = np.array([[1,1,1], [2,2,2]])
a15 = np.array([[1],[2],[3]])
print("a14=\n{}\n\na15=\n{}\n".format(a14, a15))
print("np.dot operation of matrix shapes {} and {} is a {} shaped matrix = \n{}".format(a14.shape, a15.shape, np.dot(a14,a15).shape, np.dot(a14,a15)))

a14=
[[1 1 1]
 [2 2 2]]

a15=
[[1]
 [2]
 [3]]

np.dot operation of matrix shapes (2, 3) and (3, 1) is a (2, 1) shaped matrix = 
[[ 6]
 [12]]


## Reshape

In [15]:
a = np.random.randint(low=2, high=10, size=(2, 2, 3))  # low, high give the range within which the random values are generated
print("a{}=\n{}".format(a.shape, a))
print("\na reshaped to {}=\n{}".format(a.reshape((4,3)).shape, a.reshape((4,3))))
print("\na reshaped to {}=\n{}".format(a.reshape((3,4)).shape, a.reshape((3,4))))
print("\na reshaped to {}=\n{}".format(a.reshape((2,6)).shape, a.reshape((2,6))))
a_1d = a.reshape((1,12))
print("\na reshaped to {}=\n{}".format(a_1d.shape, a_1d))
print("\na_1d reshaped to {}=\n{}".format(a_1d.reshape((2,2,3)).shape, a_1d.reshape((2,2,3))))

a(2, 2, 3)=
[[[2 2 6]
  [9 9 9]]

 [[8 2 2]
  [7 8 2]]]

a reshaped to (4, 3)=
[[2 2 6]
 [9 9 9]
 [8 2 2]
 [7 8 2]]

a reshaped to (3, 4)=
[[2 2 6 9]
 [9 9 8 2]
 [2 7 8 2]]

a reshaped to (2, 6)=
[[2 2 6 9 9 9]
 [8 2 2 7 8 2]]

a reshaped to (1, 12)=
[[2 2 6 9 9 9 8 2 2 7 8 2]]

a_1d reshaped to (2, 2, 3)=
[[[2 2 6]
  [9 9 9]]

 [[8 2 2]
  [7 8 2]]]


In [16]:
a17 = np.random.random((2,4))
print("Shape of a17={}".format(a17.shape))
print("a17=\n{}\n".format(a17))

a17_reshape = a17.reshape((1,8))
print("Shape of a17_reshape={}".format(a17_reshape.shape))
print("a17_reshape=\n{}\n".format(a17_reshape))

a17_reshape2 = a17.reshape((8,1))
print("Shape of a17_reshape2={}".format(a17_reshape2.shape))
print("a17_reshape2=\n{}\n".format(a17_reshape2))

a17_reshape3 = a17.reshape((-1,4)) # Infer the first dimension of a17 automatically (-1)
print("Shape of a17_reshape3={}".format(a17_reshape3.shape))
print("a17_reshape3=\n{}\n".format(a17_reshape3))

Shape of a17=(2, 4)
a17=
[[0.00917388 0.30683208 0.04436213 0.31775375]
 [0.7661265  0.92911555 0.34412987 0.57265574]]

Shape of a17_reshape=(1, 8)
a17_reshape=
[[0.00917388 0.30683208 0.04436213 0.31775375 0.7661265  0.92911555
  0.34412987 0.57265574]]

Shape of a17_reshape2=(8, 1)
a17_reshape2=
[[0.00917388]
 [0.30683208]
 [0.04436213]
 [0.31775375]
 [0.7661265 ]
 [0.92911555]
 [0.34412987]
 [0.57265574]]

Shape of a17_reshape3=(2, 4)
a17_reshape3=
[[0.00917388 0.30683208 0.04436213 0.31775375]
 [0.7661265  0.92911555 0.34412987 0.57265574]]



## Squeeze

In [17]:
x = np.array([[[437], [233], [99]]])
print("shape of x={}; x[0][0]={}, x[0][1]={}, x[0][2]={}".format(x.shape, x[0][0], x[0][1], x[0][2]))
x_sq = np.squeeze(x)
print("shape of x_sq={}; x_sq[0]={}, x_sq[1]={}, x_sq[2]={}".format(x_sq.shape, x_sq[0], x_sq[1], x_sq[2]))

shape of x=(1, 3, 1); x[0][0]=[437], x[0][1]=[233], x[0][2]=[99]
shape of x_sq=(3,); x_sq[0]=437, x_sq[1]=233, x_sq[2]=99


## Slicing

In [18]:
np.random.seed(67)
x = np.random.randint(9, size=(10,6))
print("x={}".format(x))
print("\nx[1::4]=\n{}".format(x[1::4]))
print("\nx[1::2]=\n{}".format(x[1::2]))
print("\nx[1:2:4]=\n{}".format(x[1:2:4]))
print("\nx[1:4:2]=\n{}".format(x[1:4:2]))

x=[[3 5 5 7 3 6]
 [3 7 8 5 3 6]
 [4 7 1 3 7 8]
 [7 2 5 5 3 2]
 [6 6 4 8 3 1]
 [4 8 2 7 0 7]
 [7 5 2 0 7 3]
 [5 1 6 1 3 4]
 [5 0 8 5 5 2]
 [8 7 6 3 4 1]]

x[1::4]=
[[3 7 8 5 3 6]
 [4 8 2 7 0 7]
 [8 7 6 3 4 1]]

x[1::2]=
[[3 7 8 5 3 6]
 [7 2 5 5 3 2]
 [4 8 2 7 0 7]
 [5 1 6 1 3 4]
 [8 7 6 3 4 1]]

x[1:2:4]=
[[3 7 8 5 3 6]]

x[1:4:2]=
[[3 7 8 5 3 6]
 [7 2 5 5 3 2]]


## Applying functions on all elements
### Square each item in the array

In [19]:
x = np.array([1, 2, 3, 4, 5])
f = lambda x: x ** 2
squares = f(x)
#print(squares)
print("squares={}\nUsing np.square(x)={}".format(squares, np.square(x)))

squares=[ 1  4  9 16 25]
Using np.square(x)=[ 1  4  9 16 25]


### Applying sigmoid function (1/(1+e^-z))

In [20]:
a = np.random.randint(20, size=(3,4))
a_sigmoid = 1/(1+np.exp(-a))
print("Applying sigmoid function to all the elements:\n{}".format(a_sigmoid))

Applying sigmoid function to all the elements:
[[0.99966465 0.5        0.73105858 0.99966465]
 [0.99999386 0.99999989 0.99999917 0.99999917]
 [0.9999833  0.99330715 0.99999989 0.98201379]]


### Return True/False based on some threshold

In [21]:
x = np.array([1, 2, 3, 4, 5])
threshold = 2.9
one_zeros = x > threshold
print(one_zeros)

[False False  True  True  True]


## Conversion

In [23]:
n = 24
print("To 1D array={}".format(np.atleast_1d(n)))
print("To 2D array={}".format(np.atleast_2d(n)))
print("To 3D array={}".format(np.atleast_3d(n)))

n = [11,22,33,44]
print("To 1D array={}".format(np.atleast_1d(n)))
print("To 2D array={}".format(np.atleast_2d(n)))
print("To 3D array={}".format(np.atleast_3d(n)))

To 1D array=[24]
To 2D array=[[24]]
To 3D array=[[[24]]]
To 1D array=[11 22 33 44]
To 2D array=[[11 22 33 44]]
To 3D array=[[[11]
  [22]
  [33]
  [44]]]


## Axes

In [36]:
# Two dimentional arrays
a = np.ones([3,5])
b = np.random.randint(1,10,[3,5])
print("a={}\n\nb={}".format(a,b))

# Summation along axis
print("\nSum of a, along axis0 = {}".format(np.sum(a,axis=0)))
print("\nSum of a, along axis1 = {}".format(np.sum(a,axis=1)))
print("\nSum of b, along axis0 = {}".format(np.sum(b,axis=0)))
print("\nSum of b, along axis1 = {}".format(np.sum(b,axis=1)))

# Concatenation along axis
print("\nConcatenate a and b along axis-0={}".format(np.concatenate([a,b], axis=0)))
print("\nConcatenate a and b along axis-1={}".format(np.concatenate([a,b], axis=1)))

a=[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

b=[[1 9 3 6 3]
 [3 4 1 8 8]
 [4 6 3 2 2]]

Sum of a, along axis0 = [3. 3. 3. 3. 3.]

Sum of a, along axis1 = [5. 5. 5.]

Sum of b, along axis0 = [ 8 19  7 16 13]

Sum of b, along axis1 = [22 24 17]

Concatenate a and b along axis-0=[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 9. 3. 6. 3.]
 [3. 4. 1. 8. 8.]
 [4. 6. 3. 2. 2.]]

Concatenate a and b along axis-1=[[1. 1. 1. 1. 1. 1. 9. 3. 6. 3.]
 [1. 1. 1. 1. 1. 3. 4. 1. 8. 8.]
 [1. 1. 1. 1. 1. 4. 6. 3. 2. 2.]]


In [39]:
# Three dimentional array
a = np.ones([3,5,2])
b = np.random.randint(1,10,[3,5,2])
print("a={}\n\nb={}".format(a,b))

# Summation along axis
print("\nSum of a, along axis0 = {}".format(np.sum(a,axis=0)))
print("\nSum of a, along axis1 = {}".format(np.sum(a,axis=1)))
print("\nSum of a, along axis2 = {}".format(np.sum(a,axis=2)))
print("\nSum of b, along axis0 = {}".format(np.sum(b,axis=0)))
print("\nSum of b, along axis1 = {}".format(np.sum(b,axis=1)))
print("\nSum of b, along axis2 = {}".format(np.sum(b,axis=2)))

# Concatenation along axis
print("\nConcatenate a and b along axis-0={}".format(np.concatenate([a,b], axis=0)))
print("\nConcatenate a and b along axis-1={}".format(np.concatenate([a,b], axis=1)))
print("\nConcatenate a and b along axis-2={}".format(np.concatenate([a,b], axis=2)))

a=[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]

b=[[[7 6]
  [7 6]
  [3 9]
  [8 5]
  [5 7]]

 [[2 2]
  [9 8]
  [3 3]
  [4 6]
  [9 7]]

 [[2 4]
  [3 7]
  [2 8]
  [6 5]
  [1 5]]]

Sum of a, along axis0 = [[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]

Sum of a, along axis1 = [[5. 5.]
 [5. 5.]
 [5. 5.]]

Sum of a, along axis2 = [[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]

Sum of b, along axis0 = [[11 12]
 [19 21]
 [ 8 20]
 [18 16]
 [15 19]]

Sum of b, along axis1 = [[30 33]
 [27 26]
 [14 29]]

Sum of b, along axis2 = [[13 13 12 13 12]
 [ 4 17  6 10 16]
 [ 6 10 10 11  6]]

Concatenate a and b along axis-0=[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[7. 6.]
  [7. 6.]
  [3. 9.]
  [8. 5.]
  [5. 7.]]

 [[2. 2.]
  [9. 8.]
  [3. 3.]
  [4. 6.]
  [9. 7.]]

 [[2. 4.]
 

# References

* [Numpy axes explained](https://www.sharpsightlabs.com/blog/numpy-axes-explained/)