In [47]:
import numpy as np

# Initializing Arrays

### Manual initialization

In [48]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Array a1={}".format(a1))
print("Array a2={}".format(a2))
print("a2[1]={}".format(a2[1]))
print("a2[1][2]={}".format(a2[1][2]))
print("Shape of a2={}".format(a2.shape))

Array a1=[1 2 3 4 5]
Array a2=[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
a2[1]=[ 6  7  8  9 10]
a2[1][2]=8
Shape of a2=(2, 5)


### Standard initialization

In [49]:
a3 = np.zeros(10) # Initialize a (1x10) array with zeros
print("a3={}".format(a3))
a4 = np.zeros((5,6)) # Initialize an (5x6) array with zeros
print("a4={}".format(a4))
# print("np.zeros(1,2)={}".format( np.zeros(1,2) )) # Error: Data type not understood

a3=[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
a4=[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [50]:
print("np.ones((6,2))={}".format(np.ones((6,2))))

np.ones((6,2))=[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [51]:
print("np.full((6,2), 99)={}".format( np.full((6,2), 99) ))

np.full((6,2), 99)=[[99 99]
 [99 99]
 [99 99]
 [99 99]
 [99 99]
 [99 99]]


In [52]:
print("np.array((4,5), dtype=np.int)={}".format(  np.array((4,5), dtype=np.int)  ))

np.array((4,5), dtype=np.int)=[4 5]


In [53]:
a4_5,a4_6 = np.zeros((2,3)), np.zeros((5,6)) # Initialize multiple matrices at the same time
print ("a4_5 = {}".format(a4_5))
print ("a4_6 = {}".format(a4_6))

a4_5 = [[0. 0. 0.]
 [0. 0. 0.]]
a4_6 = [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [54]:
print("Between 1 and 20: np.linspace(1,20,17):{}".format(np.linspace(1,20,17)))
print("\nBetween 2 and 20: np.linspace(2,20,10):{}".format(np.linspace(2,20,10)))
print("\nBetween 0 and 20: np.linspace(0,20,10):{}".format(np.linspace(0,20,10)))
print("\nBetween 1 and 5: np.linspace(1,5,5):{}".format(np.linspace(1,5,5)))
print("\nBetween 0 and 5: np.linspace(0,5,6):{}".format(np.linspace(0,5,6)))

Between 1 and 20: np.linspace(1,20,17):[ 1.      2.1875  3.375   4.5625  5.75    6.9375  8.125   9.3125 10.5
 11.6875 12.875  14.0625 15.25   16.4375 17.625  18.8125 20.    ]

Between 2 and 20: np.linspace(2,20,10):[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]

Between 0 and 20: np.linspace(0,20,10):[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]

Between 1 and 5: np.linspace(1,5,5):[1. 2. 3. 4. 5.]

Between 0 and 5: np.linspace(0,5,6):[0. 1. 2. 3. 4. 5.]


In [55]:
I1 = np.eye(4)
I2 = np.eye(4)
print("I1.I20={}\n".format(np.dot(I1,I2.T)))

I1.I20=[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]



### Random initialization

In [56]:
print("np.random.randn(2,3)=\n{}\n".format(np.random.randn(2,3) ))
print("np.random.rand(2,3)=\n{}\n".format(np.random.rand(2,3) ))
print("np.random.randint(23, size=(5,3))=\n{}\n".format(np.random.randint(23, size=(5,3)) )) # Get a 5x3 matrix randomly with integer values from (1-23)
print("np.random.randint(10, 437, 23)=\n{}\n".format(np.random.randint(10, 437, 23))) # Get a 5x3 matrix randomly with integer values from (1-23)
print("\nnp.random.random((5,5))=\n{}".format(np.random.random((5,5))))

np.random.randn(2,3)=
[[-2.07800677  1.1724973   1.934351  ]
 [ 1.83880707  1.64528246 -0.5430453 ]]

np.random.rand(2,3)=
[[0.30173678 0.17606765 0.99590107]
 [0.23051862 0.29616663 0.07323056]]

np.random.randint(23, size=(5,3))=
[[ 9 22 17]
 [ 2 18  3]
 [16  0  6]
 [21 18 21]
 [17 18  3]]

np.random.randint(10, 437, 23)=
[293 283 397  40 193 172 125 406 303 112 146 412 406 369  96 307 159 291
 308 105  64 172 369]


np.random.random((5,5))=
[[0.52364028 0.14363216 0.46049242 0.076577   0.10115818]
 [0.56136766 0.77813939 0.28480015 0.47117447 0.95224149]
 [0.52391882 0.77663788 0.62811241 0.14860888 0.55004793]
 [0.88541913 0.55977905 0.42242676 0.99106982 0.5354043 ]
 [0.11080192 0.98115022 0.73485026 0.19331022 0.90440982]]


# Modification operations

## Insert new elements

In [57]:
d = np.random.randint(1,10,size=10)
d = np.append(d,[988]) # Append an element
print(d)

[  5   6   1   6   7   8   4   9   9   2 988]


## Reshape

In [58]:
a = np.random.randint(low=2, high=10, size=(2, 2, 3))  # low, high give the range within which the random values are generated
print("a{}=\n{}".format(a.shape, a))
print("\na reshaped to {}=\n{}".format(a.reshape((4,3)).shape, a.reshape((4,3))))
print("\na reshaped to {}=\n{}".format(a.reshape((3,4)).shape, a.reshape((3,4))))
print("\na reshaped to {}=\n{}".format(a.reshape((2,6)).shape, a.reshape((2,6))))
a_1d = a.reshape((1,12))
print("\na reshaped to {}=\n{}".format(a_1d.shape, a_1d))
print("\na_1d reshaped to {}=\n{}".format(a_1d.reshape((2,2,3)).shape, a_1d.reshape((2,2,3))))

a(2, 2, 3)=
[[[6 9 3]
  [7 3 3]]

 [[6 3 2]
  [4 9 4]]]

a reshaped to (4, 3)=
[[6 9 3]
 [7 3 3]
 [6 3 2]
 [4 9 4]]

a reshaped to (3, 4)=
[[6 9 3 7]
 [3 3 6 3]
 [2 4 9 4]]

a reshaped to (2, 6)=
[[6 9 3 7 3 3]
 [6 3 2 4 9 4]]

a reshaped to (1, 12)=
[[6 9 3 7 3 3 6 3 2 4 9 4]]

a_1d reshaped to (2, 2, 3)=
[[[6 9 3]
  [7 3 3]]

 [[6 3 2]
  [4 9 4]]]


In [59]:
a17 = np.random.random((2,4))
print("Shape of a17={}".format(a17.shape))
print("a17=\n{}\n".format(a17))

a17_reshape = a17.reshape((1,8))
print("Shape of a17_reshape={}".format(a17_reshape.shape))
print("a17_reshape=\n{}\n".format(a17_reshape))

a17_reshape2 = a17.reshape((8,1))
print("Shape of a17_reshape2={}".format(a17_reshape2.shape))
print("a17_reshape2=\n{}\n".format(a17_reshape2))

a17_reshape3 = a17.reshape((-1,4)) # Infer the first dimension of a17 automatically (-1)
print("Shape of a17_reshape3={}".format(a17_reshape3.shape))
print("a17_reshape3=\n{}\n".format(a17_reshape3))

Shape of a17=(2, 4)
a17=
[[0.674972   0.03861165 0.52986955 0.25040123]
 [0.63530701 0.48645868 0.49741491 0.68933555]]

Shape of a17_reshape=(1, 8)
a17_reshape=
[[0.674972   0.03861165 0.52986955 0.25040123 0.63530701 0.48645868
  0.49741491 0.68933555]]

Shape of a17_reshape2=(8, 1)
a17_reshape2=
[[0.674972  ]
 [0.03861165]
 [0.52986955]
 [0.25040123]
 [0.63530701]
 [0.48645868]
 [0.49741491]
 [0.68933555]]

Shape of a17_reshape3=(2, 4)
a17_reshape3=
[[0.674972   0.03861165 0.52986955 0.25040123]
 [0.63530701 0.48645868 0.49741491 0.68933555]]



### Convert to other shapes using standard conversion functions

In [60]:
n = 24
print("To 1D array={}".format(np.atleast_1d(n)))
print("To 2D array={}".format(np.atleast_2d(n)))
print("To 3D array={}".format(np.atleast_3d(n)))

n = [11,22,33,44]
print("To 1D array={}".format(np.atleast_1d(n)))
print("To 2D array={}".format(np.atleast_2d(n)))
print("To 3D array={}".format(np.atleast_3d(n)))

To 1D array=[24]
To 2D array=[[24]]
To 3D array=[[[24]]]
To 1D array=[11 22 33 44]
To 2D array=[[11 22 33 44]]
To 3D array=[[[11]
  [22]
  [33]
  [44]]]


## Squeeze

In [61]:
x = np.array([[[437], [233], [99]]])
print("shape of x={}; x[0][0]={}, x[0][1]={}, x[0][2]={}".format(x.shape, x[0][0], x[0][1], x[0][2]))
x_sq = np.squeeze(x)
print("shape of x_sq={}; x_sq[0]={}, x_sq[1]={}, x_sq[2]={}".format(x_sq.shape, x_sq[0], x_sq[1], x_sq[2]))

shape of x=(1, 3, 1); x[0][0]=[437], x[0][1]=[233], x[0][2]=[99]
shape of x_sq=(3,); x_sq[0]=437, x_sq[1]=233, x_sq[2]=99


## Slicing

Syntax: x[start:stop:step]

If any of these are unspecified, they default to the values 
* start= 0
* stop = size of dimension
* step = 1

In [62]:
# Example-1
np.random.seed(67)
x = np.random.randint(9, size=(10,6))
print("x={}".format(x))
print("\nx[1::4]=\n{}".format(x[1::4]))
print("\nx[1::2]=\n{}".format(x[1::2]))
print("\nx[1:2:4]=\n{}".format(x[1:2:4]))
print("\nx[1:4:2]=\n{}".format(x[1:4:2]))

x=[[3 5 5 7 3 6]
 [3 7 8 5 3 6]
 [4 7 1 3 7 8]
 [7 2 5 5 3 2]
 [6 6 4 8 3 1]
 [4 8 2 7 0 7]
 [7 5 2 0 7 3]
 [5 1 6 1 3 4]
 [5 0 8 5 5 2]
 [8 7 6 3 4 1]]

x[1::4]=
[[3 7 8 5 3 6]
 [4 8 2 7 0 7]
 [8 7 6 3 4 1]]

x[1::2]=
[[3 7 8 5 3 6]
 [7 2 5 5 3 2]
 [4 8 2 7 0 7]
 [5 1 6 1 3 4]
 [8 7 6 3 4 1]]

x[1:2:4]=
[[3 7 8 5 3 6]]

x[1:4:2]=
[[3 7 8 5 3 6]
 [7 2 5 5 3 2]]


In [63]:
a = np.array([range(v,v+3) for v in [1, 4, 7, 10]])
b = np.array([range(v,v+3) for v in [13,16, 19, 22]])
print("a={}\nb={}\n".format(a,b))
print("First 2-rows and 3-columns of a={}".format(a[:2,:3]))
print("First 2-rows and 2-columns of a={}".format(a[:2,:2]))
print("Last 2-rows and last 2-columns of a={}".format(a[2:4:,1:3:]))
print("Last 2-rows and last 2-columns of a={}".format(a[2::,1::]))
print("Middle of matrix a={}".format(a[1:3,1:3]))

a=[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
b=[[13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]]

First 2-rows and 3-columns of a=[[1 2 3]
 [4 5 6]]
First 2-rows and 2-columns of a=[[1 2]
 [4 5]]
Last 2-rows and last 2-columns of a=[[ 8  9]
 [11 12]]
Last 2-rows and last 2-columns of a=[[ 8  9]
 [11 12]]
Middle of matrix a=[[5 6]
 [8 9]]


## Axes
### Summation

In [64]:
# Two dimentional arrays
a = np.ones([3,5])
b = np.random.randint(1,10,[3,5])
print("a={}\n\nb={}".format(a,b))

# Summation along axis
print("\nSum of a, along axis0 = {}".format(np.sum(a,axis=0)))
print("\nSum of a, along axis1 = {}".format(np.sum(a,axis=1)))
print("\nSum of b, along axis0 = {}".format(np.sum(b,axis=0)))
print("\nSum of b, along axis1 = {}".format(np.sum(b,axis=1)))

# Concatenation along axis
print("\nConcatenate a and b along axis-0={}".format(np.concatenate([a,b], axis=0)))
print("\nConcatenate a and b along axis-1={}".format(np.concatenate([a,b], axis=1)))

a=[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

b=[[5 9 1 8 8]
 [2 9 1 9 5]
 [6 1 5 9 3]]

Sum of a, along axis0 = [3. 3. 3. 3. 3.]

Sum of a, along axis1 = [5. 5. 5.]

Sum of b, along axis0 = [13 19  7 26 16]

Sum of b, along axis1 = [31 26 24]

Concatenate a and b along axis-0=[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [5. 9. 1. 8. 8.]
 [2. 9. 1. 9. 5.]
 [6. 1. 5. 9. 3.]]

Concatenate a and b along axis-1=[[1. 1. 1. 1. 1. 5. 9. 1. 8. 8.]
 [1. 1. 1. 1. 1. 2. 9. 1. 9. 5.]
 [1. 1. 1. 1. 1. 6. 1. 5. 9. 3.]]


In [65]:
# Three dimentional array
a = np.ones([3,5,2])
b = np.random.randint(1,10,[3,5,2])
print("a={}\n\nb={}".format(a,b))

# Summation along axis
print("\nSum of a, along axis0 = {}".format(np.sum(a,axis=0)))
print("\nSum of a, along axis1 = {}".format(np.sum(a,axis=1)))
print("\nSum of a, along axis2 = {}".format(np.sum(a,axis=2)))
print("\nSum of b, along axis0 = {}".format(np.sum(b,axis=0)))
print("\nSum of b, along axis1 = {}".format(np.sum(b,axis=1)))
print("\nSum of b, along axis2 = {}".format(np.sum(b,axis=2)))

# Concatenation along axis
print("\nConcatenate a and b along axis-0={}".format(np.concatenate([a,b], axis=0)))
print("\nConcatenate a and b along axis-1={}".format(np.concatenate([a,b], axis=1)))
print("\nConcatenate a and b along axis-2={}".format(np.concatenate([a,b], axis=2)))

a=[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]

b=[[[6 2]
  [8 3]
  [4 6]
  [2 7]
  [7 1]]

 [[5 5]
  [4 5]
  [1 2]
  [6 9]
  [4 9]]

 [[2 1]
  [8 5]
  [9 1]
  [5 3]
  [1 9]]]

Sum of a, along axis0 = [[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]

Sum of a, along axis1 = [[5. 5.]
 [5. 5.]
 [5. 5.]]

Sum of a, along axis2 = [[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]

Sum of b, along axis0 = [[13  8]
 [20 13]
 [14  9]
 [13 19]
 [12 19]]

Sum of b, along axis1 = [[27 19]
 [20 30]
 [25 19]]

Sum of b, along axis2 = [[ 8 11 10  9  8]
 [10  9  3 15 13]
 [ 3 13 10  8 10]]

Concatenate a and b along axis-0=[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[6. 2.]
  [8. 3.]
  [4. 6.]
  [2. 7.]
  [7. 1.]]

 [[5. 5.]
  [4. 5.]
  [1. 2.]
  [6. 9.]
  [4. 9.]]

 [[2. 1.]
 

# Array (standard) operations

In [66]:
a4 = np.random.randn(2,3)
a5 = np.exp(a4) # Create a new array, same rank as a4_3, whose values are exponential of corresponding values of a4_3
print("a5(exp of array a4)=\n{}\n".format(a5))

a5_1 = np.log(a5) # Create a new array, same rank as a5, whose values are logarithmic to the values of a5
print("a5_1(log of array a5)=\n{}".format(a5_1))
print("\nOperation 1-a5_1=\n{}\n".format(1-a5_1))

a5_2 = np.array(abs(a5)) 
print("abs of a5=\n{}".format(a5_2))

a5(exp of array a4)=
[[0.46551417 0.65284184 1.0025324 ]
 [6.88830183 2.74958237 0.92763286]]

a5_1(log of array a5)=
[[-0.76461274 -0.42642039  0.0025292 ]
 [ 1.92982459  1.01144904 -0.07511925]]

Operation 1-a5_1=
[[ 1.76461274  1.42642039  0.9974708 ]
 [-0.92982459 -0.01144904  1.07511925]]

abs of a5=
[[0.46551417 0.65284184 1.0025324 ]
 [6.88830183 2.74958237 0.92763286]]


## Copying an array into another

In [67]:
a1 = np.random.randn(2,3)
print("a1=\n{}".format(a1))
a2 = a1.copy() # Copy an array
a2 /= 2
print("Operation divide by 2 of matrix a2=\n{}".format(a2))

a1=
[[ 0.05385449 -0.1134049  -0.02924087]
 [-0.93897151 -0.58590968 -0.52851061]]
Operation divide by 2 of matrix a2=
[[ 0.02692724 -0.05670245 -0.01462043]
 [-0.46948575 -0.29295484 -0.2642553 ]]


## Elementwise mathematical operations

In [68]:
# Note that all the operations below are element wise. 

a5_2 = np.random.randint(45,size=(2,3))
a5_3 = np.ones((2,3))
print("a5_2=\n{}\n\na5_3=\n{}\n".format(a5_2, a5_3))

# Addition
print("Addition operations\n")
a5_4 = np.add(a5_2,a5_3)
print("a5_2+a5_3=\n{}\n".format(a5_4))
a5_4_1 = np.add(22,a5_3)
print("22+a5_3=\n{}\n".format(a5_4_1))
a5_4_2 = np.add(a5_3,22)
print("a5_3+22=\n{}\n".format(a5_4_2))

print("Subtraction operations\n")
a5_5 = np.subtract(a5_2,a5_3)
print("a5_2-a5_3=\n{}\n".format(a5_5))

print("Multiplication operations\n")
a5_6 = np.multiply(a5_2,a5_3) 
print("a5_2*a5_3=\n{}\n".format(a5_6))
a5_6_1 = np.multiply(437,a5_3) 
print("437*a5_3=\n{}\n".format(a5_6_1))
a5_6_2 = np.multiply(a5_3,437) 
print("a5_3*437=\n{}\n".format(a5_6_2))

print("Division operations\n")
a5_7 = np.divide(a5_2,a5_3)
print("a5_2/a5_3=\n{}\n".format(a5_7))

print("Miscelleneous operations\n")
a5_8 = np.square(a5_2)
print("elementwise (a5_2)^2=\n{}".format(a5_8))

a5_9 = np.sqrt(a5_8)
print("\nsqrt(a5_8)=\n{}".format(a5_8))

a5_2=
[[11 24  5]
 [11  3  6]]

a5_3=
[[1. 1. 1.]
 [1. 1. 1.]]

Addition operations

a5_2+a5_3=
[[12. 25.  6.]
 [12.  4.  7.]]

22+a5_3=
[[23. 23. 23.]
 [23. 23. 23.]]

a5_3+22=
[[23. 23. 23.]
 [23. 23. 23.]]

Subtraction operations

a5_2-a5_3=
[[10. 23.  4.]
 [10.  2.  5.]]

Multiplication operations

a5_2*a5_3=
[[11. 24.  5.]
 [11.  3.  6.]]

437*a5_3=
[[437. 437. 437.]
 [437. 437. 437.]]

a5_3*437=
[[437. 437. 437.]
 [437. 437. 437.]]

Division operations

a5_2/a5_3=
[[11. 24.  5.]
 [11.  3.  6.]]

Miscelleneous operations

elementwise (a5_2)^2=
[[121 576  25]
 [121   9  36]]

sqrt(a5_8)=
[[121 576  25]
 [121   9  36]]


## Matrix operations

In [69]:
a14 = np.array([[1,1,1], [2,2,2]])
a15 = np.array([[1],[2],[3]])
print("a14=\n{}\n\na15=\n{}\n".format(a14, a15))
print("np.dot operation of matrix shapes {} and {} is a {} shaped matrix = \n{}".format(a14.shape, a15.shape, np.dot(a14,a15).shape, np.dot(a14,a15)))

a14=
[[1 1 1]
 [2 2 2]]

a15=
[[1]
 [2]
 [3]]

np.dot operation of matrix shapes (2, 3) and (3, 1) is a (2, 1) shaped matrix = 
[[ 6]
 [12]]


## Applying functions on all elements
### Square each item in the array

In [70]:
x = np.array([1, 2, 3, 4, 5])
f = lambda x: x ** 2
squares = f(x)
#print(squares)
print("squares={}\nUsing np.square(x)={}".format(squares, np.square(x)))

squares=[ 1  4  9 16 25]
Using np.square(x)=[ 1  4  9 16 25]


### Applying sigmoid function (1/(1+e^-z))

In [71]:
a = np.random.randint(20, size=(3,4))
a_sigmoid = 1/(1+np.exp(-a))
print("Applying sigmoid function to all the elements:\n{}".format(a_sigmoid))

Applying sigmoid function to all the elements:
[[0.99999774 0.99987661 0.9999833  0.88079708]
 [0.99999999 0.73105858 0.99999998 0.95257413]
 [0.99999996 0.99999774 0.99752738 0.99752738]]


### Return True/False based on some threshold

In [72]:
x = np.array([1, 2, 3, 4, 5])
threshold = 2.9
one_zeros = x > threshold
print(one_zeros)

[False False  True  True  True]


# Accessing  array elements
## Individual elements of the array

In [73]:
a16 = np.array([[1,2,3,4,5,6]])
print("a16=\n{}\n\na16[0][5]={}".format(a16,a16[0][5]))

a16=
[[1 2 3 4 5 6]]

a16[0][5]=6


# References

* [Numpy axes explained](https://www.sharpsightlabs.com/blog/numpy-axes-explained/)