In [2]:
import numpy as np

In [5]:
l = [1,2,3,4]
np.array(l)

array([1, 2, 3, 4])

In [7]:
ml = [[1,2,3], [4,5,6], [7,8,9]]
np.array(ml)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.ones((2,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [19]:
np.linspace(0,400,5)

array([  0., 100., 200., 300., 400.])

In [23]:
np.linspace(0,30,11)

array([ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30.])

In [26]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Random array generation

In [31]:
np.random.rand(20) # Generate 20 uniformly distributed random numbers

array([0.11052143, 0.43224909, 0.94436012, 0.9298849 , 0.00469128,
       0.9324283 , 0.5146325 , 0.77202648, 0.88041345, 0.16962632,
       0.64449266, 0.88764369, 0.65047933, 0.00173118, 0.78076405,
       0.33520568, 0.95282303, 0.62120975, 0.66416148, 0.78840488])

In [32]:
np.random.rand(2,3)

array([[0.25221911, 0.45325202, 0.33573816],
       [0.43438134, 0.32684526, 0.88339773]])

In [42]:
np.random.randn(2,3)

array([[-0.40171836, -0.75295378,  1.38707524],
       [ 0.03646296,  0.73404995,  1.13329328]])

In [46]:
np.random.randint(2,40) # A single random number between 2-40

37

In [48]:
np.random.randint(2,40, (2,4)) # Return a 2x4 array of random number between 2-40

array([[17, 27, 18, 13],
       [15, 39, 34, 12]])

In [54]:
np.random.seed(123)
np.random.randint(2,40)

4

In [70]:
a =  np.random.randint(0,300, 12)
a

array([176, 135,  99, 180, 213, 118, 290,  76, 168, 106,  64, 278])

In [71]:
a.max()

290

In [73]:
a.argmax()

6

In [74]:
a.min()

64

In [75]:
a.argmin()

10

In [77]:
a.reshape((2,6))

array([[176, 135,  99, 180, 213, 118],
       [290,  76, 168, 106,  64, 278]])

In [78]:
a.reshape((3,4))

array([[176, 135,  99, 180],
       [213, 118, 290,  76],
       [168, 106,  64, 278]])

# Broadcasting, Slicing

In [137]:
a = np.random.randint(0,20,(4,5))
a

array([[15,  8, 13, 17,  0],
       [ 3,  1, 19,  4,  7],
       [ 6,  1, 12,  3, 12],
       [19,  7,  6,  6, 13]])

In [138]:
a[1:3]

array([[ 3,  1, 19,  4,  7],
       [ 6,  1, 12,  3, 12]])

In [139]:
a[1:3] = 10
a

array([[15,  8, 13, 17,  0],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [19,  7,  6,  6, 13]])

In [140]:
b = a[2]      # b is only a reference to the second column of a
b

array([10, 10, 10, 10, 10])

In [141]:
b[:] = 299 # Broadcasting of value 299 to the entire array of b
b

array([299, 299, 299, 299, 299])

In [142]:
a  # Notice row 2 ..

array([[ 15,   8,  13,  17,   0],
       [ 10,  10,  10,  10,  10],
       [299, 299, 299, 299, 299],
       [ 19,   7,   6,   6,  13]])

In [143]:
a[:2]

array([[15,  8, 13, 17,  0],
       [10, 10, 10, 10, 10]])

In [144]:
a[2:]

array([[299, 299, 299, 299, 299],
       [ 19,   7,   6,   6,  13]])

In [146]:
a

array([[ 15,   8,  13,  17,   0],
       [ 10,  10,  10,  10,  10],
       [299, 299, 299, 299, 299],
       [ 19,   7,   6,   6,  13]])

In [147]:
a[:2,3:] # Rows upto but not including 2, and the second argument, starting from the third column

array([[17,  0],
       [10, 10]])

In [148]:
a[:2, 2:4] # Rows upto but not including 2, and columns [2,4)

array([[13, 17],
       [10, 10]])

In [149]:
b = a[:2, :4].copy()
b

array([[15,  8, 13, 17],
       [10, 10, 10, 10]])

In [150]:
b[:] = 999
b

array([[999, 999, 999, 999],
       [999, 999, 999, 999]])

In [152]:
a

array([[ 15,   8,  13,  17,   0],
       [ 10,  10,  10,  10,  10],
       [299, 299, 299, 299, 299],
       [ 19,   7,   6,   6,  13]])

In [160]:
b = a.copy()
c = b[1:4, 1:4]
b

array([[ 15,   8,  13,  17,   0],
       [ 10,  10,  10,  10,  10],
       [299, 299, 299, 299, 299],
       [ 19,   7,   6,   6,  13]])

In [161]:
c

array([[ 10,  10,  10],
       [299, 299, 299],
       [  7,   6,   6]])

In [162]:
c == 299

array([[False, False, False],
       [ True,  True,  True],
       [False, False, False]])

In [163]:
c <=10

array([[ True,  True,  True],
       [False, False, False],
       [ True,  True,  True]])

In [172]:
c[c>=10]

array([ 10,  10,  10, 299, 299, 299])

In [173]:
c[c <= 10]

array([10, 10, 10,  7,  6,  6])

In [176]:
c+12

array([[ 22,  22,  22],
       [311, 311, 311],
       [ 19,  18,  18]])

In [179]:
c/c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [180]:
c*c # Note this is not matrix multiplication

array([[  100,   100,   100],
       [89401, 89401, 89401],
       [   49,    36,    36]])

In [184]:
np.sqrt(c)

array([[ 3.16227766,  3.16227766,  3.16227766],
       [17.29161647, 17.29161647, 17.29161647],
       [ 2.64575131,  2.44948974,  2.44948974]])

In [185]:
np.sin(c)

array([[-0.54402111, -0.54402111, -0.54402111],
       [-0.52157672, -0.52157672, -0.52157672],
       [ 0.6569866 , -0.2794155 , -0.2794155 ]])

In [186]:
c.mean()

105.11111111111111

In [187]:
c.var()

18798.765432098768

In [190]:
c.std()

137.10858992819803

In [188]:
c.max()

299

In [191]:
c.sum()

946

In [195]:
c.sum(axis=0) # Performing addition operation across the rows. The '0' index of the shape 

array([316, 315, 315])

In [199]:
c.sum(axis=1)  # Performing addition operation across the columns. The '1' index of the shape 

array([ 30, 897,  19])