In [2]:
import numpy as np

# Initializing Arrays

### Manual initialization

In [3]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Array a1={}".format(a1))
print("Array a2={}".format(a2))
print("a2[1]={}".format(a2[1]))
print("a2[1][2]={}".format(a2[1][2]))
print("Shape of a2={}".format(a2.shape))

Array a1=[1 2 3 4 5]
Array a2=[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
a2[1]=[ 6  7  8  9 10]
a2[1][2]=8
Shape of a2=(2, 5)


### Standard initialization

In [4]:
a3 = np.zeros(10) # Initialize a (1x10) array with zeros
print("a3={}".format(a3))
a4 = np.zeros((5,6)) # Initialize an (5x6) array with zeros
print("a4={}".format(a4))
# print("np.zeros(1,2)={}".format( np.zeros(1,2) )) # Error: Data type not understood

a3=[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
a4=[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [5]:
print("np.ones((6,2))={}".format(np.ones((6,2))))

np.ones((6,2))=[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [6]:
print("np.full((6,2), 99)={}".format( np.full((6,2), 99) ))

np.full((6,2), 99)=[[99 99]
 [99 99]
 [99 99]
 [99 99]
 [99 99]
 [99 99]]


In [7]:
print("np.array((4,5), dtype=np.int)={}".format(  np.array((4,5), dtype=np.int)  ))

np.array((4,5), dtype=np.int)=[4 5]


In [8]:
a4_5,a4_6 = np.zeros((2,3)), np.zeros((5,6)) # Initialize multiple matrices at the same time
print ("a4_5 = {}".format(a4_5))
print ("a4_6 = {}".format(a4_6))

a4_5 = [[0. 0. 0.]
 [0. 0. 0.]]
a4_6 = [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [9]:
print("Between 1 and 20: np.linspace(1,20,17):{}".format(np.linspace(1,20,17)))
print("\nBetween 2 and 20: np.linspace(2,20,10):{}".format(np.linspace(2,20,10)))
print("\nBetween 0 and 20: np.linspace(0,20,10):{}".format(np.linspace(0,20,10)))
print("\nBetween 1 and 5: np.linspace(1,5,5):{}".format(np.linspace(1,5,5)))
print("\nBetween 0 and 5: np.linspace(0,5,6):{}".format(np.linspace(0,5,6)))

Between 1 and 20: np.linspace(1,20,17):[ 1.      2.1875  3.375   4.5625  5.75    6.9375  8.125   9.3125 10.5
 11.6875 12.875  14.0625 15.25   16.4375 17.625  18.8125 20.    ]

Between 2 and 20: np.linspace(2,20,10):[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]

Between 0 and 20: np.linspace(0,20,10):[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]

Between 1 and 5: np.linspace(1,5,5):[1. 2. 3. 4. 5.]

Between 0 and 5: np.linspace(0,5,6):[0. 1. 2. 3. 4. 5.]


In [10]:
I1 = np.eye(4)
I2 = np.eye(4)
print("I1.I20={}\n".format(np.dot(I1,I2.T)))

I1.I20=[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]



### Random initialization

In [12]:
print("np.random.randn(2,3)=\n{}\n".format(np.random.randn(2,3) ))
print("np.random.rand(2,3)=\n{}\n".format(np.random.rand(2,3) ))
print("np.random.randint(23, size=(5,3))=\n{}\n".format(np.random.randint(23, size=(5,3)) )) # Get a 5x3 matrix randomly with integer values from (1-23)
print("np.random.randint(1, 10, size=(5,3))=\n{}\n".format(np.random.randint(1, 10, size=(5,3)) )) # Get a 5x3 matrix randomly with integer values from (1-23)
print("np.random.randint(10, 437, 10)=\n{}\n".format(np.random.randint(10, 437, 10))) # Get a 5x3 matrix randomly with integer values from (1-23)
print("\nnp.random.random((5,5))=\n{}".format(np.random.random((5,5))))

np.random.randn(2,3)=
[[ 0.1729854  -0.23018446 -1.73376285]
 [-0.10291181 -1.15753419  0.7366679 ]]

np.random.rand(2,3)=
[[0.85721208 0.09579684 0.50520592]
 [0.83850905 0.89679873 0.70624311]]

np.random.randint(23, size=(5,3))=
[[15  7  8]
 [ 4 15  3]
 [19 21  1]
 [16  7 14]
 [ 9 20 22]]

np.random.randint(1, 10, size=(5,3))=
[[8 2 4]
 [1 7 7]
 [7 2 2]
 [6 1 4]
 [4 8 1]]

np.random.randint(10, 437, 10)=
[115 101  69 222 298 282  30  13 295 377]


np.random.random((5,5))=
[[0.930246   0.9972486  0.32362088 0.48079621 0.85434553]
 [0.73210044 0.14897426 0.88338274 0.57820775 0.81942917]
 [0.12722279 0.19641367 0.97883938 0.9552197  0.70279988]
 [0.71221713 0.74297255 0.22558688 0.24353709 0.69428271]
 [0.97635947 0.05475944 0.58143659 0.95784302 0.16080295]]


# Modification operations

## Insert new elements

In [11]:
d = np.random.randint(1,10,size=10)
d = np.append(d,[988]) # Append an element
print(d)

[  3   8   9   8   7   6   6   2   2   3 988]


## Reshape

In [12]:
a = np.random.randint(low=2, high=10, size=(2, 2, 3))  # low, high give the range within which the random values are generated
print("a{}=\n{}".format(a.shape, a))
print("\na reshaped to {}=\n{}".format(a.reshape((4,3)).shape, a.reshape((4,3))))
print("\na reshaped to {}=\n{}".format(a.reshape((3,4)).shape, a.reshape((3,4))))
print("\na reshaped to {}=\n{}".format(a.reshape((2,6)).shape, a.reshape((2,6))))
a_1d = a.reshape((1,12))
print("\na reshaped to {}=\n{}".format(a_1d.shape, a_1d))
print("\na_1d reshaped to {}=\n{}".format(a_1d.reshape((2,2,3)).shape, a_1d.reshape((2,2,3))))

a(2, 2, 3)=
[[[8 8 6]
  [2 7 3]]

 [[4 2 3]
  [3 7 9]]]

a reshaped to (4, 3)=
[[8 8 6]
 [2 7 3]
 [4 2 3]
 [3 7 9]]

a reshaped to (3, 4)=
[[8 8 6 2]
 [7 3 4 2]
 [3 3 7 9]]

a reshaped to (2, 6)=
[[8 8 6 2 7 3]
 [4 2 3 3 7 9]]

a reshaped to (1, 12)=
[[8 8 6 2 7 3 4 2 3 3 7 9]]

a_1d reshaped to (2, 2, 3)=
[[[8 8 6]
  [2 7 3]]

 [[4 2 3]
  [3 7 9]]]


In [13]:
a17 = np.random.random((2,4))
print("Shape of a17={}".format(a17.shape))
print("a17=\n{}\n".format(a17))

a17_reshape = a17.reshape((1,8))
print("Shape of a17_reshape={}".format(a17_reshape.shape))
print("a17_reshape=\n{}\n".format(a17_reshape))

a17_reshape2 = a17.reshape((8,1))
print("Shape of a17_reshape2={}".format(a17_reshape2.shape))
print("a17_reshape2=\n{}\n".format(a17_reshape2))

a17_reshape3 = a17.reshape((-1,4)) # Infer the first dimension of a17 automatically (-1)
print("Shape of a17_reshape3={}".format(a17_reshape3.shape))
print("a17_reshape3=\n{}\n".format(a17_reshape3))

Shape of a17=(2, 4)
a17=
[[0.15411116 0.70457204 0.9041644  0.46583428]
 [0.18151368 0.19198195 0.36905187 0.07553664]]

Shape of a17_reshape=(1, 8)
a17_reshape=
[[0.15411116 0.70457204 0.9041644  0.46583428 0.18151368 0.19198195
  0.36905187 0.07553664]]

Shape of a17_reshape2=(8, 1)
a17_reshape2=
[[0.15411116]
 [0.70457204]
 [0.9041644 ]
 [0.46583428]
 [0.18151368]
 [0.19198195]
 [0.36905187]
 [0.07553664]]

Shape of a17_reshape3=(2, 4)
a17_reshape3=
[[0.15411116 0.70457204 0.9041644  0.46583428]
 [0.18151368 0.19198195 0.36905187 0.07553664]]



### Convert to other shapes using standard conversion functions

In [14]:
n = 24
print("To 1D array={}".format(np.atleast_1d(n)))
print("To 2D array={}".format(np.atleast_2d(n)))
print("To 3D array={}".format(np.atleast_3d(n)))

n = [11,22,33,44]
print("To 1D array={}".format(np.atleast_1d(n)))
print("To 2D array={}".format(np.atleast_2d(n)))
print("To 3D array={}".format(np.atleast_3d(n)))

To 1D array=[24]
To 2D array=[[24]]
To 3D array=[[[24]]]
To 1D array=[11 22 33 44]
To 2D array=[[11 22 33 44]]
To 3D array=[[[11]
  [22]
  [33]
  [44]]]


## Squeeze

In [15]:
x = np.array([[[437], [233], [99]]])
print("shape of x={}; x[0][0]={}, x[0][1]={}, x[0][2]={}".format(x.shape, x[0][0], x[0][1], x[0][2]))
x_sq = np.squeeze(x)
print("shape of x_sq={}; x_sq[0]={}, x_sq[1]={}, x_sq[2]={}".format(x_sq.shape, x_sq[0], x_sq[1], x_sq[2]))

shape of x=(1, 3, 1); x[0][0]=[437], x[0][1]=[233], x[0][2]=[99]
shape of x_sq=(3,); x_sq[0]=437, x_sq[1]=233, x_sq[2]=99


## Fancy Indexing

In [16]:
np.random.seed(34)
a = np.arange(1,20)
b = np.arange(100,104)
indices = np.random.randint(1, 20, size=4, dtype=np.int)
print("a={}, b={}, indices={}".format(a,b,indices))

# 1. Replacing the 'indices' of the array 'a' with values of 'b'
print("############################# Example-1 ##############################")
a[indices] = b
print("a={}".format(a))

# 2. 
print("############################# Example-2 ##############################")
a = np.arange(20).reshape((4,5))
row = np.array([0,2,3])
col = np.array([1,2,3])
print("a={}, row={}, col={}".format(a, row, col))
print("a[{}]={}".format(row,a[row]))
print("a[{},{}]={}".format(row,col,a[row,col]))
print("a[row[:,np.newaxis], col]={}".format(a[row[:,np.newaxis], col]))
print("row[:,np.newaxis]*col={}".format(row[:,np.newaxis]*col))
print("a[:,{}]={}".format(col,a[:,col]))
print("a[2:,{}]={}".format(col,a[2:,col]))
b=a.copy()
b[2:,col]=437
print("After a[2:,{}]=437: {}".format(col,b))


a=[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19], b=[100 101 102 103], indices=[ 2 11 10  5]
############################# Example-1 ##############################
a=[  1   2 100   4   5 103   7   8   9  10 102 101  13  14  15  16  17  18
  19]
############################# Example-2 ##############################
a=[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]], row=[0 2 3], col=[1 2 3]
a[[0 2 3]]=[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]]
a[[0 2 3],[1 2 3]]=[ 1 12 18]
a[row[:,np.newaxis], col]=[[ 1  2  3]
 [11 12 13]
 [16 17 18]]
row[:,np.newaxis]*col=[[0 0 0]
 [2 4 6]
 [3 6 9]]
a[:,[1 2 3]]=[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]]
a[2:,[1 2 3]]=[[11 12 13]
 [16 17 18]]
After a[2:,[1 2 3]]=437: [[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10 437 437 437  14]
 [ 15 437 437 437  19]]


## Slicing

Syntax: x[start:stop:step]

If any of these are unspecified, they default to the values 
* start= 0
* stop = size of dimension
* step = 1

In [17]:
# Example-1
np.random.seed(67)
x = np.random.randint(9, size=(10,6))
print("x={}".format(x))
print("\nx[1::4]=\n{}".format(x[1::4]))
print("\nx[1::2]=\n{}".format(x[1::2]))
print("\nx[1:2:4]=\n{}".format(x[1:2:4]))
print("\nx[1:4:2]=\n{}".format(x[1:4:2]))

x=[[3 5 5 7 3 6]
 [3 7 8 5 3 6]
 [4 7 1 3 7 8]
 [7 2 5 5 3 2]
 [6 6 4 8 3 1]
 [4 8 2 7 0 7]
 [7 5 2 0 7 3]
 [5 1 6 1 3 4]
 [5 0 8 5 5 2]
 [8 7 6 3 4 1]]

x[1::4]=
[[3 7 8 5 3 6]
 [4 8 2 7 0 7]
 [8 7 6 3 4 1]]

x[1::2]=
[[3 7 8 5 3 6]
 [7 2 5 5 3 2]
 [4 8 2 7 0 7]
 [5 1 6 1 3 4]
 [8 7 6 3 4 1]]

x[1:2:4]=
[[3 7 8 5 3 6]]

x[1:4:2]=
[[3 7 8 5 3 6]
 [7 2 5 5 3 2]]


In [18]:
a = np.array([range(v,v+3) for v in [1, 4, 7, 10]])
b = np.array([range(v,v+3) for v in [13,16, 19, 22]])
print("a={}\nb={}\n".format(a,b))
print("First 2-rows and 3-columns of a={}".format(a[:2,:3]))
print("First 2-rows and 2-columns of a={}".format(a[:2,:2]))
print("Last 2-rows and last 2-columns of a={}".format(a[2:4:,1:3:]))
print("Last 2-rows and last 2-columns of a={}".format(a[2::,1::]))
print("Middle of matrix a={}".format(a[1:3,1:3]))

a=[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
b=[[13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]]

First 2-rows and 3-columns of a=[[1 2 3]
 [4 5 6]]
First 2-rows and 2-columns of a=[[1 2]
 [4 5]]
Last 2-rows and last 2-columns of a=[[ 8  9]
 [11 12]]
Last 2-rows and last 2-columns of a=[[ 8  9]
 [11 12]]
Middle of matrix a=[[5 6]
 [8 9]]


In [19]:
a = np.arange(1,12)
print("a={}\na[2:6]={}\na[:6]={}\na[2:]={}\na[2:10:2]={}".format(a,a[2:6],a[:6],a[2:],a[2:10:2]))

a=[ 1  2  3  4  5  6  7  8  9 10 11]
a[2:6]=[3 4 5 6]
a[:6]=[1 2 3 4 5 6]
a[2:]=[ 3  4  5  6  7  8  9 10 11]
a[2:10:2]=[3 5 7 9]


# Sorting

In [20]:
np.random.seed(437)

print("######################## Example-1 ##############################")
a = np.random.randint(1,100,size=(4,6))
print("a={}\nnp.sort(a)={}".format(a,np.sort(a)))
print("np.sort(a,axis=0)={}".format(np.sort(a,axis=0)))
print("np.sort(a,axis=0)={}".format(np.sort(a,axis=0)))
print("np.argsort(a,axis=0)={}".format(np.argsort(a,axis=0))) # Sorted indices of the array along axis=0

print("######################## Example-2 ##############################")
b = np.random.randint(1,100,20)
print("b={}".format(b))
print("np.partition(b,5)={}".format(np.partition(b,5))) # Get '5' smallest numbers of the array. Note the order is arbitrary.

######################## Example-1 ##############################
a=[[12 87 52 24 91 35]
 [94 73  7 18 58 19]
 [84 54 95 83  6 67]
 [51 30 45 58 32 35]]
np.sort(a)=[[12 24 35 52 87 91]
 [ 7 18 19 58 73 94]
 [ 6 54 67 83 84 95]
 [30 32 35 45 51 58]]
np.sort(a,axis=0)=[[12 30  7 18  6 19]
 [51 54 45 24 32 35]
 [84 73 52 58 58 35]
 [94 87 95 83 91 67]]
np.sort(a,axis=0)=[[12 30  7 18  6 19]
 [51 54 45 24 32 35]
 [84 73 52 58 58 35]
 [94 87 95 83 91 67]]
np.argsort(a,axis=0)=[[0 3 1 1 2 1]
 [3 2 3 0 3 0]
 [2 1 0 3 1 3]
 [1 0 2 2 0 2]]
######################## Example-2 ##############################
b=[80 92 14 78 64 40 71  4 39 68  7  6 63 50 32 90 59  1 61  9]
np.partition(b,5)=[ 7  4  1  6  9 14 32 40 39 59 64 61 63 50 68 90 92 71 78 80]


## Axes
### Summation

In [21]:
# Two dimentional arrays
a = np.ones([3,5])
b = np.random.randint(1,10,[3,5])
print("a={}\n\nb={}".format(a,b))

# Summation along axis
print("\nSum of a, along axis0 = {}".format(np.sum(a,axis=0)))
print("\nSum of a, along axis1 = {}".format(np.sum(a,axis=1)))
print("\nSum of b, along axis0 = {}".format(np.sum(b,axis=0)))
print("\nSum of b, along axis1 = {}".format(np.sum(b,axis=1)))

# Concatenation along axis
print("\nConcatenate a and b along axis-0={}".format(np.concatenate([a,b], axis=0)))
print("\nConcatenate a and b along axis-1={}".format(np.concatenate([a,b], axis=1)))

a=[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

b=[[2 8 3 8 4]
 [6 4 6 3 7]
 [9 4 4 9 5]]

Sum of a, along axis0 = [3. 3. 3. 3. 3.]

Sum of a, along axis1 = [5. 5. 5.]

Sum of b, along axis0 = [17 16 13 20 16]

Sum of b, along axis1 = [25 26 31]

Concatenate a and b along axis-0=[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 8. 3. 8. 4.]
 [6. 4. 6. 3. 7.]
 [9. 4. 4. 9. 5.]]

Concatenate a and b along axis-1=[[1. 1. 1. 1. 1. 2. 8. 3. 8. 4.]
 [1. 1. 1. 1. 1. 6. 4. 6. 3. 7.]
 [1. 1. 1. 1. 1. 9. 4. 4. 9. 5.]]


In [22]:
# Three dimentional array
a = np.ones([3,5,2])
b = np.random.randint(1,10,[3,5,2])
print("a={}\n\nb={}".format(a,b))

# Summation along axis
print("\nSum of a, along axis0 = {}".format(np.sum(a,axis=0)))
print("\nSum of a, along axis1 = {}".format(np.sum(a,axis=1)))
print("\nSum of a, along axis2 = {}".format(np.sum(a,axis=2)))
print("\nSum of b, along axis0 = {}".format(np.sum(b,axis=0)))
print("\nSum of b, along axis1 = {}".format(np.sum(b,axis=1)))
print("\nSum of b, along axis2 = {}".format(np.sum(b,axis=2)))

# Concatenation along axis
print("\nConcatenate a and b along axis-0={}".format(np.concatenate([a,b], axis=0)))
print("\nConcatenate a and b along axis-1={}".format(np.concatenate([a,b], axis=1)))
print("\nConcatenate a and b along axis-2={}".format(np.concatenate([a,b], axis=2)))

a=[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]

b=[[[9 7]
  [8 3]
  [2 3]
  [6 5]
  [4 7]]

 [[9 8]
  [3 6]
  [6 7]
  [8 1]
  [3 6]]

 [[4 3]
  [9 9]
  [3 5]
  [1 3]
  [1 1]]]

Sum of a, along axis0 = [[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]

Sum of a, along axis1 = [[5. 5.]
 [5. 5.]
 [5. 5.]]

Sum of a, along axis2 = [[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]

Sum of b, along axis0 = [[22 18]
 [20 18]
 [11 15]
 [15  9]
 [ 8 14]]

Sum of b, along axis1 = [[29 25]
 [29 28]
 [18 21]]

Sum of b, along axis2 = [[16 11  5 11 11]
 [17  9 13  9  9]
 [ 7 18  8  4  2]]

Concatenate a and b along axis-0=[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[9. 7.]
  [8. 3.]
  [2. 3.]
  [6. 5.]
  [4. 7.]]

 [[9. 8.]
  [3. 6.]
  [6. 7.]
  [8. 1.]
  [3. 6.]]

 [[4. 3.]
 

# Array (standard) operations

In [23]:
a4 = np.random.randn(2,3)
a5 = np.exp(a4) # Create a new array, same rank as a4_3, whose values are exponential of corresponding values of a4_3
print("a5(exp of array a4)=\n{}\n".format(a5))

a5_1 = np.log(a5) # Create a new array, same rank as a5, whose values are logarithmic to the values of a5
print("a5_1(log of array a5)=\n{}".format(a5_1))
print("\nOperation 1-a5_1=\n{}\n".format(1-a5_1))

a5_2 = np.array(abs(a5)) 
print("abs of a5=\n{}".format(a5_2))

a5(exp of array a4)=
[[0.39166158 0.46022621 0.62245334]
 [3.38106198 1.46092065 1.1471382 ]]

a5_1(log of array a5)=
[[-0.93735713 -0.77603714 -0.4740866 ]
 [ 1.21818986  0.37906682  0.13727032]]

Operation 1-a5_1=
[[ 1.93735713  1.77603714  1.4740866 ]
 [-0.21818986  0.62093318  0.86272968]]

abs of a5=
[[0.39166158 0.46022621 0.62245334]
 [3.38106198 1.46092065 1.1471382 ]]


## Copying an array into another

In [24]:
a1 = np.random.randn(2,3)
print("a1=\n{}".format(a1))
a2 = a1.copy() # Copy an array
a2 /= 2
print("Operation divide by 2 of matrix a2=\n{}".format(a2))

a1=
[[ 0.428448   -1.07117863 -1.34181127]
 [-0.77704065  1.98305074 -0.65109272]]
Operation divide by 2 of matrix a2=
[[ 0.214224   -0.53558932 -0.67090564]
 [-0.38852033  0.99152537 -0.32554636]]


## Elementwise mathematical operations

In [25]:
# Note that all the operations below are element wise. 

a5_2 = np.random.randint(45,size=(2,3))
a5_3 = np.ones((2,3))
print("a5_2=\n{}\n\na5_3=\n{}\n".format(a5_2, a5_3))

# Addition
print("Addition operations\n")
a5_4 = np.add(a5_2,a5_3)
print("a5_2+a5_3=\n{}\n".format(a5_4))
a5_4_1 = np.add(22,a5_3)
print("22+a5_3=\n{}\n".format(a5_4_1))
a5_4_2 = np.add(a5_3,22)
print("a5_3+22=\n{}\n".format(a5_4_2))

print("Subtraction operations\n")
a5_5 = np.subtract(a5_2,a5_3)
print("a5_2-a5_3=\n{}\n".format(a5_5))

print("Multiplication operations\n")
a5_6 = np.multiply(a5_2,a5_3) 
print("a5_2*a5_3=\n{}\n".format(a5_6))
a5_6_1 = np.multiply(437,a5_3) 
print("437*a5_3=\n{}\n".format(a5_6_1))
a5_6_2 = np.multiply(a5_3,437) 
print("a5_3*437=\n{}\n".format(a5_6_2))

print("Division operations\n")
a5_7 = np.divide(a5_2,a5_3)
print("a5_2/a5_3=\n{}\n".format(a5_7))

print("Miscelleneous operations\n")
a5_8 = np.square(a5_2)
print("elementwise (a5_2)^2=\n{}".format(a5_8))

a5_9 = np.sqrt(a5_8)
print("\nsqrt(a5_8)=\n{}".format(a5_8))

a5_2=
[[14  3 37]
 [34 19 26]]

a5_3=
[[1. 1. 1.]
 [1. 1. 1.]]

Addition operations

a5_2+a5_3=
[[15.  4. 38.]
 [35. 20. 27.]]

22+a5_3=
[[23. 23. 23.]
 [23. 23. 23.]]

a5_3+22=
[[23. 23. 23.]
 [23. 23. 23.]]

Subtraction operations

a5_2-a5_3=
[[13.  2. 36.]
 [33. 18. 25.]]

Multiplication operations

a5_2*a5_3=
[[14.  3. 37.]
 [34. 19. 26.]]

437*a5_3=
[[437. 437. 437.]
 [437. 437. 437.]]

a5_3*437=
[[437. 437. 437.]
 [437. 437. 437.]]

Division operations

a5_2/a5_3=
[[14.  3. 37.]
 [34. 19. 26.]]

Miscelleneous operations

elementwise (a5_2)^2=
[[ 196    9 1369]
 [1156  361  676]]

sqrt(a5_8)=
[[ 196    9 1369]
 [1156  361  676]]


## Matrix operations

In [26]:
a14 = np.array([[1,1,1], [2,2,2]])
a15 = np.array([[1],[2],[3]])
print("a14=\n{}\n\na15=\n{}\n".format(a14, a15))
print("np.dot operation of matrix shapes {} and {} is a {} shaped matrix = \n{}".format(a14.shape, a15.shape, np.dot(a14,a15).shape, np.dot(a14,a15)))

a14=
[[1 1 1]
 [2 2 2]]

a15=
[[1]
 [2]
 [3]]

np.dot operation of matrix shapes (2, 3) and (3, 1) is a (2, 1) shaped matrix = 
[[ 6]
 [12]]


## Applying functions on all elements
### Square each item in the array

In [27]:
x = np.array([1, 2, 3, 4, 5])
f = lambda x: x ** 2
squares = f(x)
#print(squares)
print("squares={}\nUsing np.square(x)={}".format(squares, np.square(x)))

squares=[ 1  4  9 16 25]
Using np.square(x)=[ 1  4  9 16 25]


### Applying sigmoid function (1/(1+e^-z))

In [28]:
a = np.random.randint(20, size=(3,4))
a_sigmoid = 1/(1+np.exp(-a))
print("Applying sigmoid function to all the elements:\n{}".format(a_sigmoid))

Applying sigmoid function to all the elements:
[[0.99987661 0.99999996 0.9999546  0.99999999]
 [0.99999774 0.99999917 0.99999989 0.99999386]
 [0.99987661 0.98201379 0.9999833  0.99330715]]


### Return True/False based on some threshold

In [29]:
x = np.array([1, 2, 3, 4, 5])
threshold = 2.9
one_zeros = x > threshold
print(one_zeros)

[False False  True  True  True]


# Accessing  array elements
## Individual elements of the array

In [30]:
a16 = np.array([[1,2,3,4,5,6]])
print("a16=\n{}\n\na16[0][5]={}".format(a16,a16[0][5]))

a16=
[[1 2 3 4 5 6]]

a16[0][5]=6


# Structured data

In [37]:
name = ["Alice", "Grace", "Tom", "Vim"]
age = [31,42,53,64]
weight = [70.2,45.34,54.23,32]
a = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
                       'formats':('U10','i4','f8')})
a['name'] = name
a['age'] = age
a['weight'] = weight
print("a={}".format(a))
print("a['age']={}  a['name']={}".format(a['age'], a['name']))
print("a[0]={}".format(a[0]))  # Note the difference to the Pandas dataframe object which cannot be accessed 
                               # row-wise, where as here it is possible

a=[('Alice', 31, 70.2 ) ('Grace', 42, 45.34) ('Tom', 53, 54.23)
 ('Vim', 64, 32.  )]
a['age']=[31 42 53 64]  a['name']=['Alice' 'Grace' 'Tom' 'Vim']
a[0]=('Alice', 31, 70.2)


# References

* [Numpy axes explained](https://www.sharpsightlabs.com/blog/numpy-axes-explained/)